package com.xjtlu.bio.entity;

import java.util.Date;

public class BioAnalysisPipeline {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_analysis_pipeline.pipeline_id
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    private Long pipelineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_analysis_pipeline.pipeline_type
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    private Integer pipelineType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_analysis_pipeline.status
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_analysis_pipeline.analysis_pipeline_name
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    private String analysisPipelineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_analysis_pipeline.CREATE_TIME
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_analysis_pipeline.project_id
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_analysis_pipeline.pipeline_parameters
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    private String pipelineParameters;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_analysis_pipeline.pipeline_id
     *
     * @return the value of bio_analysis_pipeline.pipeline_id
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    public Long getPipelineId() {
        return pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_analysis_pipeline.pipeline_id
     *
     * @param pipelineId the value for bio_analysis_pipeline.pipeline_id
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    public void setPipelineId(Long pipelineId) {
        this.pipelineId = pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_analysis_pipeline.pipeline_type
     *
     * @return the value of bio_analysis_pipeline.pipeline_type
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    public Integer getPipelineType() {
        return pipelineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_analysis_pipeline.pipeline_type
     *
     * @param pipelineType the value for bio_analysis_pipeline.pipeline_type
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    public void setPipelineType(Integer pipelineType) {
        this.pipelineType = pipelineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_analysis_pipeline.status
     *
     * @return the value of bio_analysis_pipeline.status
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_analysis_pipeline.status
     *
     * @param status the value for bio_analysis_pipeline.status
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_analysis_pipeline.analysis_pipeline_name
     *
     * @return the value of bio_analysis_pipeline.analysis_pipeline_name
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    public String getAnalysisPipelineName() {
        return analysisPipelineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_analysis_pipeline.analysis_pipeline_name
     *
     * @param analysisPipelineName the value for bio_analysis_pipeline.analysis_pipeline_name
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    public void setAnalysisPipelineName(String analysisPipelineName) {
        this.analysisPipelineName = analysisPipelineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_analysis_pipeline.CREATE_TIME
     *
     * @return the value of bio_analysis_pipeline.CREATE_TIME
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_analysis_pipeline.CREATE_TIME
     *
     * @param createTime the value for bio_analysis_pipeline.CREATE_TIME
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_analysis_pipeline.project_id
     *
     * @return the value of bio_analysis_pipeline.project_id
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_analysis_pipeline.project_id
     *
     * @param projectId the value for bio_analysis_pipeline.project_id
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_analysis_pipeline.pipeline_parameters
     *
     * @return the value of bio_analysis_pipeline.pipeline_parameters
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    public String getPipelineParameters() {
        return pipelineParameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_analysis_pipeline.pipeline_parameters
     *
     * @param pipelineParameters the value for bio_analysis_pipeline.pipeline_parameters
     *
     * @mbg.generated Tue Mar 31 13:52:56 EDT 2026
     */
    public void setPipelineParameters(String pipelineParameters) {
        this.pipelineParameters = pipelineParameters;
    }
}