package com.xjtlu.bio.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BioAnalysisPipelineExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    public BioAnalysisPipelineExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPipelineIdIsNull() {
            addCriterion("pipeline_id is null");
            return (Criteria) this;
        }

        public Criteria andPipelineIdIsNotNull() {
            addCriterion("pipeline_id is not null");
            return (Criteria) this;
        }

        public Criteria andPipelineIdEqualTo(Long value) {
            addCriterion("pipeline_id =", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdNotEqualTo(Long value) {
            addCriterion("pipeline_id <>", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdGreaterThan(Long value) {
            addCriterion("pipeline_id >", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdGreaterThanOrEqualTo(Long value) {
            addCriterion("pipeline_id >=", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdLessThan(Long value) {
            addCriterion("pipeline_id <", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdLessThanOrEqualTo(Long value) {
            addCriterion("pipeline_id <=", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdIn(List<Long> values) {
            addCriterion("pipeline_id in", values, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdNotIn(List<Long> values) {
            addCriterion("pipeline_id not in", values, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdBetween(Long value1, Long value2) {
            addCriterion("pipeline_id between", value1, value2, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdNotBetween(Long value1, Long value2) {
            addCriterion("pipeline_id not between", value1, value2, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineTypeIsNull() {
            addCriterion("pipeline_type is null");
            return (Criteria) this;
        }

        public Criteria andPipelineTypeIsNotNull() {
            addCriterion("pipeline_type is not null");
            return (Criteria) this;
        }

        public Criteria andPipelineTypeEqualTo(Integer value) {
            addCriterion("pipeline_type =", value, "pipelineType");
            return (Criteria) this;
        }

        public Criteria andPipelineTypeNotEqualTo(Integer value) {
            addCriterion("pipeline_type <>", value, "pipelineType");
            return (Criteria) this;
        }

        public Criteria andPipelineTypeGreaterThan(Integer value) {
            addCriterion("pipeline_type >", value, "pipelineType");
            return (Criteria) this;
        }

        public Criteria andPipelineTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("pipeline_type >=", value, "pipelineType");
            return (Criteria) this;
        }

        public Criteria andPipelineTypeLessThan(Integer value) {
            addCriterion("pipeline_type <", value, "pipelineType");
            return (Criteria) this;
        }

        public Criteria andPipelineTypeLessThanOrEqualTo(Integer value) {
            addCriterion("pipeline_type <=", value, "pipelineType");
            return (Criteria) this;
        }

        public Criteria andPipelineTypeIn(List<Integer> values) {
            addCriterion("pipeline_type in", values, "pipelineType");
            return (Criteria) this;
        }

        public Criteria andPipelineTypeNotIn(List<Integer> values) {
            addCriterion("pipeline_type not in", values, "pipelineType");
            return (Criteria) this;
        }

        public Criteria andPipelineTypeBetween(Integer value1, Integer value2) {
            addCriterion("pipeline_type between", value1, value2, "pipelineType");
            return (Criteria) this;
        }

        public Criteria andPipelineTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("pipeline_type not between", value1, value2, "pipelineType");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andAnalysisPipelineNameIsNull() {
            addCriterion("analysis_pipeline_name is null");
            return (Criteria) this;
        }

        public Criteria andAnalysisPipelineNameIsNotNull() {
            addCriterion("analysis_pipeline_name is not null");
            return (Criteria) this;
        }

        public Criteria andAnalysisPipelineNameEqualTo(String value) {
            addCriterion("analysis_pipeline_name =", value, "analysisPipelineName");
            return (Criteria) this;
        }

        public Criteria andAnalysisPipelineNameNotEqualTo(String value) {
            addCriterion("analysis_pipeline_name <>", value, "analysisPipelineName");
            return (Criteria) this;
        }

        public Criteria andAnalysisPipelineNameGreaterThan(String value) {
            addCriterion("analysis_pipeline_name >", value, "analysisPipelineName");
            return (Criteria) this;
        }

        public Criteria andAnalysisPipelineNameGreaterThanOrEqualTo(String value) {
            addCriterion("analysis_pipeline_name >=", value, "analysisPipelineName");
            return (Criteria) this;
        }

        public Criteria andAnalysisPipelineNameLessThan(String value) {
            addCriterion("analysis_pipeline_name <", value, "analysisPipelineName");
            return (Criteria) this;
        }

        public Criteria andAnalysisPipelineNameLessThanOrEqualTo(String value) {
            addCriterion("analysis_pipeline_name <=", value, "analysisPipelineName");
            return (Criteria) this;
        }

        public Criteria andAnalysisPipelineNameLike(String value) {
            addCriterion("analysis_pipeline_name like", value, "analysisPipelineName");
            return (Criteria) this;
        }

        public Criteria andAnalysisPipelineNameNotLike(String value) {
            addCriterion("analysis_pipeline_name not like", value, "analysisPipelineName");
            return (Criteria) this;
        }

        public Criteria andAnalysisPipelineNameIn(List<String> values) {
            addCriterion("analysis_pipeline_name in", values, "analysisPipelineName");
            return (Criteria) this;
        }

        public Criteria andAnalysisPipelineNameNotIn(List<String> values) {
            addCriterion("analysis_pipeline_name not in", values, "analysisPipelineName");
            return (Criteria) this;
        }

        public Criteria andAnalysisPipelineNameBetween(String value1, String value2) {
            addCriterion("analysis_pipeline_name between", value1, value2, "analysisPipelineName");
            return (Criteria) this;
        }

        public Criteria andAnalysisPipelineNameNotBetween(String value1, String value2) {
            addCriterion("analysis_pipeline_name not between", value1, value2, "analysisPipelineName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Long value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Long value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Long value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Long value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Long value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Long> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Long> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Long value1, Long value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Long value1, Long value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andParentPipelineIdIsNull() {
            addCriterion("parent_pipeline_id is null");
            return (Criteria) this;
        }

        public Criteria andParentPipelineIdIsNotNull() {
            addCriterion("parent_pipeline_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentPipelineIdEqualTo(Long value) {
            addCriterion("parent_pipeline_id =", value, "parentPipelineId");
            return (Criteria) this;
        }

        public Criteria andParentPipelineIdNotEqualTo(Long value) {
            addCriterion("parent_pipeline_id <>", value, "parentPipelineId");
            return (Criteria) this;
        }

        public Criteria andParentPipelineIdGreaterThan(Long value) {
            addCriterion("parent_pipeline_id >", value, "parentPipelineId");
            return (Criteria) this;
        }

        public Criteria andParentPipelineIdGreaterThanOrEqualTo(Long value) {
            addCriterion("parent_pipeline_id >=", value, "parentPipelineId");
            return (Criteria) this;
        }

        public Criteria andParentPipelineIdLessThan(Long value) {
            addCriterion("parent_pipeline_id <", value, "parentPipelineId");
            return (Criteria) this;
        }

        public Criteria andParentPipelineIdLessThanOrEqualTo(Long value) {
            addCriterion("parent_pipeline_id <=", value, "parentPipelineId");
            return (Criteria) this;
        }

        public Criteria andParentPipelineIdIn(List<Long> values) {
            addCriterion("parent_pipeline_id in", values, "parentPipelineId");
            return (Criteria) this;
        }

        public Criteria andParentPipelineIdNotIn(List<Long> values) {
            addCriterion("parent_pipeline_id not in", values, "parentPipelineId");
            return (Criteria) this;
        }

        public Criteria andParentPipelineIdBetween(Long value1, Long value2) {
            addCriterion("parent_pipeline_id between", value1, value2, "parentPipelineId");
            return (Criteria) this;
        }

        public Criteria andParentPipelineIdNotBetween(Long value1, Long value2) {
            addCriterion("parent_pipeline_id not between", value1, value2, "parentPipelineId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 05 22:53:29 EDT 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sun Apr 05 22:53:29 EDT 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}