package com.xjtlu.bio.entity;

public class BioAnalysisPipeline {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_analysis_pipeline.pipeline_id
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    private Long pipelineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_analysis_pipeline.pipeline_type
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    private Integer pipelineType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_analysis_pipeline.pipeline_id
     *
     * @return the value of bio_analysis_pipeline.pipeline_id
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public Long getPipelineId() {
        return pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_analysis_pipeline.pipeline_id
     *
     * @param pipelineId the value for bio_analysis_pipeline.pipeline_id
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public void setPipelineId(Long pipelineId) {
        this.pipelineId = pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_analysis_pipeline.pipeline_type
     *
     * @return the value of bio_analysis_pipeline.pipeline_type
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public Integer getPipelineType() {
        return pipelineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_analysis_pipeline.pipeline_type
     *
     * @param pipelineType the value for bio_analysis_pipeline.pipeline_type
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public void setPipelineType(Integer pipelineType) {
        this.pipelineType = pipelineType;
    }
}