package com.xjtlu.bio.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BioPipelineStageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public BioPipelineStageExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStageIdIsNull() {
            addCriterion("stage_id is null");
            return (Criteria) this;
        }

        public Criteria andStageIdIsNotNull() {
            addCriterion("stage_id is not null");
            return (Criteria) this;
        }

        public Criteria andStageIdEqualTo(Integer value) {
            addCriterion("stage_id =", value, "stageId");
            return (Criteria) this;
        }

        public Criteria andStageIdNotEqualTo(Integer value) {
            addCriterion("stage_id <>", value, "stageId");
            return (Criteria) this;
        }

        public Criteria andStageIdGreaterThan(Integer value) {
            addCriterion("stage_id >", value, "stageId");
            return (Criteria) this;
        }

        public Criteria andStageIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("stage_id >=", value, "stageId");
            return (Criteria) this;
        }

        public Criteria andStageIdLessThan(Integer value) {
            addCriterion("stage_id <", value, "stageId");
            return (Criteria) this;
        }

        public Criteria andStageIdLessThanOrEqualTo(Integer value) {
            addCriterion("stage_id <=", value, "stageId");
            return (Criteria) this;
        }

        public Criteria andStageIdIn(List<Integer> values) {
            addCriterion("stage_id in", values, "stageId");
            return (Criteria) this;
        }

        public Criteria andStageIdNotIn(List<Integer> values) {
            addCriterion("stage_id not in", values, "stageId");
            return (Criteria) this;
        }

        public Criteria andStageIdBetween(Integer value1, Integer value2) {
            addCriterion("stage_id between", value1, value2, "stageId");
            return (Criteria) this;
        }

        public Criteria andStageIdNotBetween(Integer value1, Integer value2) {
            addCriterion("stage_id not between", value1, value2, "stageId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdIsNull() {
            addCriterion("pipeline_id is null");
            return (Criteria) this;
        }

        public Criteria andPipelineIdIsNotNull() {
            addCriterion("pipeline_id is not null");
            return (Criteria) this;
        }

        public Criteria andPipelineIdEqualTo(Integer value) {
            addCriterion("pipeline_id =", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdNotEqualTo(Integer value) {
            addCriterion("pipeline_id <>", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdGreaterThan(Integer value) {
            addCriterion("pipeline_id >", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pipeline_id >=", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdLessThan(Integer value) {
            addCriterion("pipeline_id <", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdLessThanOrEqualTo(Integer value) {
            addCriterion("pipeline_id <=", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdIn(List<Integer> values) {
            addCriterion("pipeline_id in", values, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdNotIn(List<Integer> values) {
            addCriterion("pipeline_id not in", values, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdBetween(Integer value1, Integer value2) {
            addCriterion("pipeline_id between", value1, value2, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pipeline_id not between", value1, value2, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andStageIndexIsNull() {
            addCriterion("stage_index is null");
            return (Criteria) this;
        }

        public Criteria andStageIndexIsNotNull() {
            addCriterion("stage_index is not null");
            return (Criteria) this;
        }

        public Criteria andStageIndexEqualTo(Integer value) {
            addCriterion("stage_index =", value, "stageIndex");
            return (Criteria) this;
        }

        public Criteria andStageIndexNotEqualTo(Integer value) {
            addCriterion("stage_index <>", value, "stageIndex");
            return (Criteria) this;
        }

        public Criteria andStageIndexGreaterThan(Integer value) {
            addCriterion("stage_index >", value, "stageIndex");
            return (Criteria) this;
        }

        public Criteria andStageIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("stage_index >=", value, "stageIndex");
            return (Criteria) this;
        }

        public Criteria andStageIndexLessThan(Integer value) {
            addCriterion("stage_index <", value, "stageIndex");
            return (Criteria) this;
        }

        public Criteria andStageIndexLessThanOrEqualTo(Integer value) {
            addCriterion("stage_index <=", value, "stageIndex");
            return (Criteria) this;
        }

        public Criteria andStageIndexIn(List<Integer> values) {
            addCriterion("stage_index in", values, "stageIndex");
            return (Criteria) this;
        }

        public Criteria andStageIndexNotIn(List<Integer> values) {
            addCriterion("stage_index not in", values, "stageIndex");
            return (Criteria) this;
        }

        public Criteria andStageIndexBetween(Integer value1, Integer value2) {
            addCriterion("stage_index between", value1, value2, "stageIndex");
            return (Criteria) this;
        }

        public Criteria andStageIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("stage_index not between", value1, value2, "stageIndex");
            return (Criteria) this;
        }

        public Criteria andStageNameIsNull() {
            addCriterion("stage_name is null");
            return (Criteria) this;
        }

        public Criteria andStageNameIsNotNull() {
            addCriterion("stage_name is not null");
            return (Criteria) this;
        }

        public Criteria andStageNameEqualTo(String value) {
            addCriterion("stage_name =", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameNotEqualTo(String value) {
            addCriterion("stage_name <>", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameGreaterThan(String value) {
            addCriterion("stage_name >", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameGreaterThanOrEqualTo(String value) {
            addCriterion("stage_name >=", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameLessThan(String value) {
            addCriterion("stage_name <", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameLessThanOrEqualTo(String value) {
            addCriterion("stage_name <=", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameLike(String value) {
            addCriterion("stage_name like", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameNotLike(String value) {
            addCriterion("stage_name not like", value, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameIn(List<String> values) {
            addCriterion("stage_name in", values, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameNotIn(List<String> values) {
            addCriterion("stage_name not in", values, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameBetween(String value1, String value2) {
            addCriterion("stage_name between", value1, value2, "stageName");
            return (Criteria) this;
        }

        public Criteria andStageNameNotBetween(String value1, String value2) {
            addCriterion("stage_name not between", value1, value2, "stageName");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andInputUrlIsNull() {
            addCriterion("input_url is null");
            return (Criteria) this;
        }

        public Criteria andInputUrlIsNotNull() {
            addCriterion("input_url is not null");
            return (Criteria) this;
        }

        public Criteria andInputUrlEqualTo(String value) {
            addCriterion("input_url =", value, "inputUrl");
            return (Criteria) this;
        }

        public Criteria andInputUrlNotEqualTo(String value) {
            addCriterion("input_url <>", value, "inputUrl");
            return (Criteria) this;
        }

        public Criteria andInputUrlGreaterThan(String value) {
            addCriterion("input_url >", value, "inputUrl");
            return (Criteria) this;
        }

        public Criteria andInputUrlGreaterThanOrEqualTo(String value) {
            addCriterion("input_url >=", value, "inputUrl");
            return (Criteria) this;
        }

        public Criteria andInputUrlLessThan(String value) {
            addCriterion("input_url <", value, "inputUrl");
            return (Criteria) this;
        }

        public Criteria andInputUrlLessThanOrEqualTo(String value) {
            addCriterion("input_url <=", value, "inputUrl");
            return (Criteria) this;
        }

        public Criteria andInputUrlLike(String value) {
            addCriterion("input_url like", value, "inputUrl");
            return (Criteria) this;
        }

        public Criteria andInputUrlNotLike(String value) {
            addCriterion("input_url not like", value, "inputUrl");
            return (Criteria) this;
        }

        public Criteria andInputUrlIn(List<String> values) {
            addCriterion("input_url in", values, "inputUrl");
            return (Criteria) this;
        }

        public Criteria andInputUrlNotIn(List<String> values) {
            addCriterion("input_url not in", values, "inputUrl");
            return (Criteria) this;
        }

        public Criteria andInputUrlBetween(String value1, String value2) {
            addCriterion("input_url between", value1, value2, "inputUrl");
            return (Criteria) this;
        }

        public Criteria andInputUrlNotBetween(String value1, String value2) {
            addCriterion("input_url not between", value1, value2, "inputUrl");
            return (Criteria) this;
        }

        public Criteria andOutputUrlIsNull() {
            addCriterion("output_url is null");
            return (Criteria) this;
        }

        public Criteria andOutputUrlIsNotNull() {
            addCriterion("output_url is not null");
            return (Criteria) this;
        }

        public Criteria andOutputUrlEqualTo(String value) {
            addCriterion("output_url =", value, "outputUrl");
            return (Criteria) this;
        }

        public Criteria andOutputUrlNotEqualTo(String value) {
            addCriterion("output_url <>", value, "outputUrl");
            return (Criteria) this;
        }

        public Criteria andOutputUrlGreaterThan(String value) {
            addCriterion("output_url >", value, "outputUrl");
            return (Criteria) this;
        }

        public Criteria andOutputUrlGreaterThanOrEqualTo(String value) {
            addCriterion("output_url >=", value, "outputUrl");
            return (Criteria) this;
        }

        public Criteria andOutputUrlLessThan(String value) {
            addCriterion("output_url <", value, "outputUrl");
            return (Criteria) this;
        }

        public Criteria andOutputUrlLessThanOrEqualTo(String value) {
            addCriterion("output_url <=", value, "outputUrl");
            return (Criteria) this;
        }

        public Criteria andOutputUrlLike(String value) {
            addCriterion("output_url like", value, "outputUrl");
            return (Criteria) this;
        }

        public Criteria andOutputUrlNotLike(String value) {
            addCriterion("output_url not like", value, "outputUrl");
            return (Criteria) this;
        }

        public Criteria andOutputUrlIn(List<String> values) {
            addCriterion("output_url in", values, "outputUrl");
            return (Criteria) this;
        }

        public Criteria andOutputUrlNotIn(List<String> values) {
            addCriterion("output_url not in", values, "outputUrl");
            return (Criteria) this;
        }

        public Criteria andOutputUrlBetween(String value1, String value2) {
            addCriterion("output_url between", value1, value2, "outputUrl");
            return (Criteria) this;
        }

        public Criteria andOutputUrlNotBetween(String value1, String value2) {
            addCriterion("output_url not between", value1, value2, "outputUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated do_not_delete_during_merge Sat Oct 25 00:37:22 GMT 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}