package com.xjtlu.bio.entity;

import java.util.Date;

public class BioPipelineInputFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_input_file.input_file_id
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    private Long inputFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_input_file.pipeline_id
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    private Long pipelineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_input_file.file_role
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    private Integer fileRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_input_file.file_name
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_input_file.original_filename
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    private String originalFilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_input_file.file_path
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_input_file.status
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_input_file.create_time
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_input_file.input_file_id
     *
     * @return the value of bio_pipeline_input_file.input_file_id
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public Long getInputFileId() {
        return inputFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_input_file.input_file_id
     *
     * @param inputFileId the value for bio_pipeline_input_file.input_file_id
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public void setInputFileId(Long inputFileId) {
        this.inputFileId = inputFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_input_file.pipeline_id
     *
     * @return the value of bio_pipeline_input_file.pipeline_id
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public Long getPipelineId() {
        return pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_input_file.pipeline_id
     *
     * @param pipelineId the value for bio_pipeline_input_file.pipeline_id
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public void setPipelineId(Long pipelineId) {
        this.pipelineId = pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_input_file.file_role
     *
     * @return the value of bio_pipeline_input_file.file_role
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public Integer getFileRole() {
        return fileRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_input_file.file_role
     *
     * @param fileRole the value for bio_pipeline_input_file.file_role
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public void setFileRole(Integer fileRole) {
        this.fileRole = fileRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_input_file.file_name
     *
     * @return the value of bio_pipeline_input_file.file_name
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_input_file.file_name
     *
     * @param fileName the value for bio_pipeline_input_file.file_name
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_input_file.original_filename
     *
     * @return the value of bio_pipeline_input_file.original_filename
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public String getOriginalFilename() {
        return originalFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_input_file.original_filename
     *
     * @param originalFilename the value for bio_pipeline_input_file.original_filename
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public void setOriginalFilename(String originalFilename) {
        this.originalFilename = originalFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_input_file.file_path
     *
     * @return the value of bio_pipeline_input_file.file_path
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_input_file.file_path
     *
     * @param filePath the value for bio_pipeline_input_file.file_path
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_input_file.status
     *
     * @return the value of bio_pipeline_input_file.status
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_input_file.status
     *
     * @param status the value for bio_pipeline_input_file.status
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_input_file.create_time
     *
     * @return the value of bio_pipeline_input_file.create_time
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_input_file.create_time
     *
     * @param createTime the value for bio_pipeline_input_file.create_time
     *
     * @mbg.generated Wed Mar 25 15:41:37 EDT 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}