package com.xjtlu.bio.entity;

import java.util.Date;

public class BioPipelineStage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_stage.stage_id
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    private Integer stageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_stage.pipeline_id
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    private Integer pipelineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_stage.stage_index
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    private Integer stageIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_stage.stage_name
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    private String stageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_stage.status
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_stage.start_time
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_stage.end_time
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_stage.input_url
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    private String inputUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_pipeline_stage.output_url
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    private String outputUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_stage.stage_id
     *
     * @return the value of bio_pipeline_stage.stage_id
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public Integer getStageId() {
        return stageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_stage.stage_id
     *
     * @param stageId the value for bio_pipeline_stage.stage_id
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public void setStageId(Integer stageId) {
        this.stageId = stageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_stage.pipeline_id
     *
     * @return the value of bio_pipeline_stage.pipeline_id
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public Integer getPipelineId() {
        return pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_stage.pipeline_id
     *
     * @param pipelineId the value for bio_pipeline_stage.pipeline_id
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public void setPipelineId(Integer pipelineId) {
        this.pipelineId = pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_stage.stage_index
     *
     * @return the value of bio_pipeline_stage.stage_index
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public Integer getStageIndex() {
        return stageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_stage.stage_index
     *
     * @param stageIndex the value for bio_pipeline_stage.stage_index
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public void setStageIndex(Integer stageIndex) {
        this.stageIndex = stageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_stage.stage_name
     *
     * @return the value of bio_pipeline_stage.stage_name
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public String getStageName() {
        return stageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_stage.stage_name
     *
     * @param stageName the value for bio_pipeline_stage.stage_name
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public void setStageName(String stageName) {
        this.stageName = stageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_stage.status
     *
     * @return the value of bio_pipeline_stage.status
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_stage.status
     *
     * @param status the value for bio_pipeline_stage.status
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_stage.start_time
     *
     * @return the value of bio_pipeline_stage.start_time
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_stage.start_time
     *
     * @param startTime the value for bio_pipeline_stage.start_time
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_stage.end_time
     *
     * @return the value of bio_pipeline_stage.end_time
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_stage.end_time
     *
     * @param endTime the value for bio_pipeline_stage.end_time
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_stage.input_url
     *
     * @return the value of bio_pipeline_stage.input_url
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public String getInputUrl() {
        return inputUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_stage.input_url
     *
     * @param inputUrl the value for bio_pipeline_stage.input_url
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public void setInputUrl(String inputUrl) {
        this.inputUrl = inputUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_pipeline_stage.output_url
     *
     * @return the value of bio_pipeline_stage.output_url
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public String getOutputUrl() {
        return outputUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_pipeline_stage.output_url
     *
     * @param outputUrl the value for bio_pipeline_stage.output_url
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    public void setOutputUrl(String outputUrl) {
        this.outputUrl = outputUrl;
    }
}