package com.xjtlu.bio.entity;

public class BioProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_project.pid
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_project.project_name
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_project.description
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_project.created_by
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    private Integer createdBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_project.pid
     *
     * @return the value of bio_project.pid
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_project.pid
     *
     * @param pid the value for bio_project.pid
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_project.project_name
     *
     * @return the value of bio_project.project_name
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_project.project_name
     *
     * @param projectName the value for bio_project.project_name
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_project.description
     *
     * @return the value of bio_project.description
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_project.description
     *
     * @param description the value for bio_project.description
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_project.created_by
     *
     * @return the value of bio_project.created_by
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_project.created_by
     *
     * @param createdBy the value for bio_project.created_by
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
}