package com.xjtlu.bio.entity;

import java.util.ArrayList;
import java.util.List;

public class BioRefseqExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public BioRefseqExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRefIdIsNull() {
            addCriterion("ref_id is null");
            return (Criteria) this;
        }

        public Criteria andRefIdIsNotNull() {
            addCriterion("ref_id is not null");
            return (Criteria) this;
        }

        public Criteria andRefIdEqualTo(Long value) {
            addCriterion("ref_id =", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdNotEqualTo(Long value) {
            addCriterion("ref_id <>", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdGreaterThan(Long value) {
            addCriterion("ref_id >", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ref_id >=", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdLessThan(Long value) {
            addCriterion("ref_id <", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdLessThanOrEqualTo(Long value) {
            addCriterion("ref_id <=", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdIn(List<Long> values) {
            addCriterion("ref_id in", values, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdNotIn(List<Long> values) {
            addCriterion("ref_id not in", values, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdBetween(Long value1, Long value2) {
            addCriterion("ref_id between", value1, value2, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdNotBetween(Long value1, Long value2) {
            addCriterion("ref_id not between", value1, value2, "refId");
            return (Criteria) this;
        }

        public Criteria andRefseqNameIsNull() {
            addCriterion("refseq_name is null");
            return (Criteria) this;
        }

        public Criteria andRefseqNameIsNotNull() {
            addCriterion("refseq_name is not null");
            return (Criteria) this;
        }

        public Criteria andRefseqNameEqualTo(String value) {
            addCriterion("refseq_name =", value, "refseqName");
            return (Criteria) this;
        }

        public Criteria andRefseqNameNotEqualTo(String value) {
            addCriterion("refseq_name <>", value, "refseqName");
            return (Criteria) this;
        }

        public Criteria andRefseqNameGreaterThan(String value) {
            addCriterion("refseq_name >", value, "refseqName");
            return (Criteria) this;
        }

        public Criteria andRefseqNameGreaterThanOrEqualTo(String value) {
            addCriterion("refseq_name >=", value, "refseqName");
            return (Criteria) this;
        }

        public Criteria andRefseqNameLessThan(String value) {
            addCriterion("refseq_name <", value, "refseqName");
            return (Criteria) this;
        }

        public Criteria andRefseqNameLessThanOrEqualTo(String value) {
            addCriterion("refseq_name <=", value, "refseqName");
            return (Criteria) this;
        }

        public Criteria andRefseqNameLike(String value) {
            addCriterion("refseq_name like", value, "refseqName");
            return (Criteria) this;
        }

        public Criteria andRefseqNameNotLike(String value) {
            addCriterion("refseq_name not like", value, "refseqName");
            return (Criteria) this;
        }

        public Criteria andRefseqNameIn(List<String> values) {
            addCriterion("refseq_name in", values, "refseqName");
            return (Criteria) this;
        }

        public Criteria andRefseqNameNotIn(List<String> values) {
            addCriterion("refseq_name not in", values, "refseqName");
            return (Criteria) this;
        }

        public Criteria andRefseqNameBetween(String value1, String value2) {
            addCriterion("refseq_name between", value1, value2, "refseqName");
            return (Criteria) this;
        }

        public Criteria andRefseqNameNotBetween(String value1, String value2) {
            addCriterion("refseq_name not between", value1, value2, "refseqName");
            return (Criteria) this;
        }

        public Criteria andOrgTypeIsNull() {
            addCriterion("org_type is null");
            return (Criteria) this;
        }

        public Criteria andOrgTypeIsNotNull() {
            addCriterion("org_type is not null");
            return (Criteria) this;
        }

        public Criteria andOrgTypeEqualTo(Integer value) {
            addCriterion("org_type =", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeNotEqualTo(Integer value) {
            addCriterion("org_type <>", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeGreaterThan(Integer value) {
            addCriterion("org_type >", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("org_type >=", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeLessThan(Integer value) {
            addCriterion("org_type <", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeLessThanOrEqualTo(Integer value) {
            addCriterion("org_type <=", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeIn(List<Integer> values) {
            addCriterion("org_type in", values, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeNotIn(List<Integer> values) {
            addCriterion("org_type not in", values, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeBetween(Integer value1, Integer value2) {
            addCriterion("org_type between", value1, value2, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("org_type not between", value1, value2, "orgType");
            return (Criteria) this;
        }

        public Criteria andSourceDbIsNull() {
            addCriterion("source_db is null");
            return (Criteria) this;
        }

        public Criteria andSourceDbIsNotNull() {
            addCriterion("source_db is not null");
            return (Criteria) this;
        }

        public Criteria andSourceDbEqualTo(String value) {
            addCriterion("source_db =", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbNotEqualTo(String value) {
            addCriterion("source_db <>", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbGreaterThan(String value) {
            addCriterion("source_db >", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbGreaterThanOrEqualTo(String value) {
            addCriterion("source_db >=", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbLessThan(String value) {
            addCriterion("source_db <", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbLessThanOrEqualTo(String value) {
            addCriterion("source_db <=", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbLike(String value) {
            addCriterion("source_db like", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbNotLike(String value) {
            addCriterion("source_db not like", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbIn(List<String> values) {
            addCriterion("source_db in", values, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbNotIn(List<String> values) {
            addCriterion("source_db not in", values, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbBetween(String value1, String value2) {
            addCriterion("source_db between", value1, value2, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbNotBetween(String value1, String value2) {
            addCriterion("source_db not between", value1, value2, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andRefseqPathIsNull() {
            addCriterion("refseq_path is null");
            return (Criteria) this;
        }

        public Criteria andRefseqPathIsNotNull() {
            addCriterion("refseq_path is not null");
            return (Criteria) this;
        }

        public Criteria andRefseqPathEqualTo(String value) {
            addCriterion("refseq_path =", value, "refseqPath");
            return (Criteria) this;
        }

        public Criteria andRefseqPathNotEqualTo(String value) {
            addCriterion("refseq_path <>", value, "refseqPath");
            return (Criteria) this;
        }

        public Criteria andRefseqPathGreaterThan(String value) {
            addCriterion("refseq_path >", value, "refseqPath");
            return (Criteria) this;
        }

        public Criteria andRefseqPathGreaterThanOrEqualTo(String value) {
            addCriterion("refseq_path >=", value, "refseqPath");
            return (Criteria) this;
        }

        public Criteria andRefseqPathLessThan(String value) {
            addCriterion("refseq_path <", value, "refseqPath");
            return (Criteria) this;
        }

        public Criteria andRefseqPathLessThanOrEqualTo(String value) {
            addCriterion("refseq_path <=", value, "refseqPath");
            return (Criteria) this;
        }

        public Criteria andRefseqPathLike(String value) {
            addCriterion("refseq_path like", value, "refseqPath");
            return (Criteria) this;
        }

        public Criteria andRefseqPathNotLike(String value) {
            addCriterion("refseq_path not like", value, "refseqPath");
            return (Criteria) this;
        }

        public Criteria andRefseqPathIn(List<String> values) {
            addCriterion("refseq_path in", values, "refseqPath");
            return (Criteria) this;
        }

        public Criteria andRefseqPathNotIn(List<String> values) {
            addCriterion("refseq_path not in", values, "refseqPath");
            return (Criteria) this;
        }

        public Criteria andRefseqPathBetween(String value1, String value2) {
            addCriterion("refseq_path between", value1, value2, "refseqPath");
            return (Criteria) this;
        }

        public Criteria andRefseqPathNotBetween(String value1, String value2) {
            addCriterion("refseq_path not between", value1, value2, "refseqPath");
            return (Criteria) this;
        }

        public Criteria andTaxIdIsNull() {
            addCriterion("tax_id is null");
            return (Criteria) this;
        }

        public Criteria andTaxIdIsNotNull() {
            addCriterion("tax_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaxIdEqualTo(Integer value) {
            addCriterion("tax_id =", value, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdNotEqualTo(Integer value) {
            addCriterion("tax_id <>", value, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdGreaterThan(Integer value) {
            addCriterion("tax_id >", value, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tax_id >=", value, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdLessThan(Integer value) {
            addCriterion("tax_id <", value, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdLessThanOrEqualTo(Integer value) {
            addCriterion("tax_id <=", value, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdIn(List<Integer> values) {
            addCriterion("tax_id in", values, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdNotIn(List<Integer> values) {
            addCriterion("tax_id not in", values, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdBetween(Integer value1, Integer value2) {
            addCriterion("tax_id between", value1, value2, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tax_id not between", value1, value2, "taxId");
            return (Criteria) this;
        }

        public Criteria andAccessionsIsNull() {
            addCriterion("accessions is null");
            return (Criteria) this;
        }

        public Criteria andAccessionsIsNotNull() {
            addCriterion("accessions is not null");
            return (Criteria) this;
        }

        public Criteria andAccessionsEqualTo(String value) {
            addCriterion("accessions =", value, "accessions");
            return (Criteria) this;
        }

        public Criteria andAccessionsNotEqualTo(String value) {
            addCriterion("accessions <>", value, "accessions");
            return (Criteria) this;
        }

        public Criteria andAccessionsGreaterThan(String value) {
            addCriterion("accessions >", value, "accessions");
            return (Criteria) this;
        }

        public Criteria andAccessionsGreaterThanOrEqualTo(String value) {
            addCriterion("accessions >=", value, "accessions");
            return (Criteria) this;
        }

        public Criteria andAccessionsLessThan(String value) {
            addCriterion("accessions <", value, "accessions");
            return (Criteria) this;
        }

        public Criteria andAccessionsLessThanOrEqualTo(String value) {
            addCriterion("accessions <=", value, "accessions");
            return (Criteria) this;
        }

        public Criteria andAccessionsLike(String value) {
            addCriterion("accessions like", value, "accessions");
            return (Criteria) this;
        }

        public Criteria andAccessionsNotLike(String value) {
            addCriterion("accessions not like", value, "accessions");
            return (Criteria) this;
        }

        public Criteria andAccessionsIn(List<String> values) {
            addCriterion("accessions in", values, "accessions");
            return (Criteria) this;
        }

        public Criteria andAccessionsNotIn(List<String> values) {
            addCriterion("accessions not in", values, "accessions");
            return (Criteria) this;
        }

        public Criteria andAccessionsBetween(String value1, String value2) {
            addCriterion("accessions between", value1, value2, "accessions");
            return (Criteria) this;
        }

        public Criteria andAccessionsNotBetween(String value1, String value2) {
            addCriterion("accessions not between", value1, value2, "accessions");
            return (Criteria) this;
        }

        public Criteria andIsSegmentIsNull() {
            addCriterion("is_segment is null");
            return (Criteria) this;
        }

        public Criteria andIsSegmentIsNotNull() {
            addCriterion("is_segment is not null");
            return (Criteria) this;
        }

        public Criteria andIsSegmentEqualTo(Boolean value) {
            addCriterion("is_segment =", value, "isSegment");
            return (Criteria) this;
        }

        public Criteria andIsSegmentNotEqualTo(Boolean value) {
            addCriterion("is_segment <>", value, "isSegment");
            return (Criteria) this;
        }

        public Criteria andIsSegmentGreaterThan(Boolean value) {
            addCriterion("is_segment >", value, "isSegment");
            return (Criteria) this;
        }

        public Criteria andIsSegmentGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_segment >=", value, "isSegment");
            return (Criteria) this;
        }

        public Criteria andIsSegmentLessThan(Boolean value) {
            addCriterion("is_segment <", value, "isSegment");
            return (Criteria) this;
        }

        public Criteria andIsSegmentLessThanOrEqualTo(Boolean value) {
            addCriterion("is_segment <=", value, "isSegment");
            return (Criteria) this;
        }

        public Criteria andIsSegmentIn(List<Boolean> values) {
            addCriterion("is_segment in", values, "isSegment");
            return (Criteria) this;
        }

        public Criteria andIsSegmentNotIn(List<Boolean> values) {
            addCriterion("is_segment not in", values, "isSegment");
            return (Criteria) this;
        }

        public Criteria andIsSegmentBetween(Boolean value1, Boolean value2) {
            addCriterion("is_segment between", value1, value2, "isSegment");
            return (Criteria) this;
        }

        public Criteria andIsSegmentNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_segment not between", value1, value2, "isSegment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bio_refseq
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 17 16:17:39 EDT 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}