package com.xjtlu.bio.entity;

import java.util.Date;

public class BioReferenceSequence {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.reference_id
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private Long referenceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.accession
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private String accession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.source_db
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private String sourceDb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.tax_id
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private Integer taxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.organism_name
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private String organismName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.genome_length
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private Integer genomeLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.completeness
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private String completeness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.is_annotated
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private Boolean isAnnotated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.gene_count
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private Integer geneCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.protein_count
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private Integer proteinCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.segment
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private String segment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.bioproject
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private String bioproject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.release_date
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private Date releaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.update_date
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.org_type
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private Integer orgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.path
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.annotation_file
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private String annotationFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_reference_sequence.raw_metadata
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    private String rawMetadata;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.reference_id
     *
     * @return the value of bio_reference_sequence.reference_id
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public Long getReferenceId() {
        return referenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.reference_id
     *
     * @param referenceId the value for bio_reference_sequence.reference_id
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setReferenceId(Long referenceId) {
        this.referenceId = referenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.accession
     *
     * @return the value of bio_reference_sequence.accession
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public String getAccession() {
        return accession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.accession
     *
     * @param accession the value for bio_reference_sequence.accession
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setAccession(String accession) {
        this.accession = accession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.source_db
     *
     * @return the value of bio_reference_sequence.source_db
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public String getSourceDb() {
        return sourceDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.source_db
     *
     * @param sourceDb the value for bio_reference_sequence.source_db
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setSourceDb(String sourceDb) {
        this.sourceDb = sourceDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.tax_id
     *
     * @return the value of bio_reference_sequence.tax_id
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public Integer getTaxId() {
        return taxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.tax_id
     *
     * @param taxId the value for bio_reference_sequence.tax_id
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setTaxId(Integer taxId) {
        this.taxId = taxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.organism_name
     *
     * @return the value of bio_reference_sequence.organism_name
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public String getOrganismName() {
        return organismName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.organism_name
     *
     * @param organismName the value for bio_reference_sequence.organism_name
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setOrganismName(String organismName) {
        this.organismName = organismName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.genome_length
     *
     * @return the value of bio_reference_sequence.genome_length
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public Integer getGenomeLength() {
        return genomeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.genome_length
     *
     * @param genomeLength the value for bio_reference_sequence.genome_length
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setGenomeLength(Integer genomeLength) {
        this.genomeLength = genomeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.completeness
     *
     * @return the value of bio_reference_sequence.completeness
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public String getCompleteness() {
        return completeness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.completeness
     *
     * @param completeness the value for bio_reference_sequence.completeness
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setCompleteness(String completeness) {
        this.completeness = completeness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.is_annotated
     *
     * @return the value of bio_reference_sequence.is_annotated
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public Boolean getIsAnnotated() {
        return isAnnotated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.is_annotated
     *
     * @param isAnnotated the value for bio_reference_sequence.is_annotated
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setIsAnnotated(Boolean isAnnotated) {
        this.isAnnotated = isAnnotated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.gene_count
     *
     * @return the value of bio_reference_sequence.gene_count
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public Integer getGeneCount() {
        return geneCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.gene_count
     *
     * @param geneCount the value for bio_reference_sequence.gene_count
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setGeneCount(Integer geneCount) {
        this.geneCount = geneCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.protein_count
     *
     * @return the value of bio_reference_sequence.protein_count
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public Integer getProteinCount() {
        return proteinCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.protein_count
     *
     * @param proteinCount the value for bio_reference_sequence.protein_count
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setProteinCount(Integer proteinCount) {
        this.proteinCount = proteinCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.segment
     *
     * @return the value of bio_reference_sequence.segment
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public String getSegment() {
        return segment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.segment
     *
     * @param segment the value for bio_reference_sequence.segment
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setSegment(String segment) {
        this.segment = segment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.bioproject
     *
     * @return the value of bio_reference_sequence.bioproject
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public String getBioproject() {
        return bioproject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.bioproject
     *
     * @param bioproject the value for bio_reference_sequence.bioproject
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setBioproject(String bioproject) {
        this.bioproject = bioproject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.release_date
     *
     * @return the value of bio_reference_sequence.release_date
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.release_date
     *
     * @param releaseDate the value for bio_reference_sequence.release_date
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.update_date
     *
     * @return the value of bio_reference_sequence.update_date
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.update_date
     *
     * @param updateDate the value for bio_reference_sequence.update_date
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.org_type
     *
     * @return the value of bio_reference_sequence.org_type
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public Integer getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.org_type
     *
     * @param orgType the value for bio_reference_sequence.org_type
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setOrgType(Integer orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.path
     *
     * @return the value of bio_reference_sequence.path
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.path
     *
     * @param path the value for bio_reference_sequence.path
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.annotation_file
     *
     * @return the value of bio_reference_sequence.annotation_file
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public String getAnnotationFile() {
        return annotationFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.annotation_file
     *
     * @param annotationFile the value for bio_reference_sequence.annotation_file
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setAnnotationFile(String annotationFile) {
        this.annotationFile = annotationFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_reference_sequence.raw_metadata
     *
     * @return the value of bio_reference_sequence.raw_metadata
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public String getRawMetadata() {
        return rawMetadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_reference_sequence.raw_metadata
     *
     * @param rawMetadata the value for bio_reference_sequence.raw_metadata
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    public void setRawMetadata(String rawMetadata) {
        this.rawMetadata = rawMetadata;
    }
}