package com.xjtlu.bio.entity;

public class BioRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_role.rid
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_role.role_name
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_role.description
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_role.rid
     *
     * @return the value of bio_role.rid
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_role.rid
     *
     * @param rid the value for bio_role.rid
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_role.role_name
     *
     * @return the value of bio_role.role_name
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_role.role_name
     *
     * @param roleName the value for bio_role.role_name
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_role.description
     *
     * @return the value of bio_role.description
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_role.description
     *
     * @param description the value for bio_role.description
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }
}