package com.xjtlu.bio.entity;

public class BioRefseq {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq.ref_id
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    private Long refId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq.refseq_name
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    private String refseqName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq.org_type
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    private Integer orgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq.source_db
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    private String sourceDb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq.refseq_path
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    private String refseqPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq.tax_id
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    private Integer taxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq.accessions
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    private String accessions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq.is_segment
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    private Boolean isSegment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq.meta
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    private String meta;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq.ref_id
     *
     * @return the value of bio_refseq.ref_id
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public Long getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq.ref_id
     *
     * @param refId the value for bio_refseq.ref_id
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public void setRefId(Long refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq.refseq_name
     *
     * @return the value of bio_refseq.refseq_name
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public String getRefseqName() {
        return refseqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq.refseq_name
     *
     * @param refseqName the value for bio_refseq.refseq_name
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public void setRefseqName(String refseqName) {
        this.refseqName = refseqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq.org_type
     *
     * @return the value of bio_refseq.org_type
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public Integer getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq.org_type
     *
     * @param orgType the value for bio_refseq.org_type
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public void setOrgType(Integer orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq.source_db
     *
     * @return the value of bio_refseq.source_db
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public String getSourceDb() {
        return sourceDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq.source_db
     *
     * @param sourceDb the value for bio_refseq.source_db
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public void setSourceDb(String sourceDb) {
        this.sourceDb = sourceDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq.refseq_path
     *
     * @return the value of bio_refseq.refseq_path
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public String getRefseqPath() {
        return refseqPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq.refseq_path
     *
     * @param refseqPath the value for bio_refseq.refseq_path
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public void setRefseqPath(String refseqPath) {
        this.refseqPath = refseqPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq.tax_id
     *
     * @return the value of bio_refseq.tax_id
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public Integer getTaxId() {
        return taxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq.tax_id
     *
     * @param taxId the value for bio_refseq.tax_id
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public void setTaxId(Integer taxId) {
        this.taxId = taxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq.accessions
     *
     * @return the value of bio_refseq.accessions
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public String getAccessions() {
        return accessions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq.accessions
     *
     * @param accessions the value for bio_refseq.accessions
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public void setAccessions(String accessions) {
        this.accessions = accessions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq.is_segment
     *
     * @return the value of bio_refseq.is_segment
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public Boolean getIsSegment() {
        return isSegment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq.is_segment
     *
     * @param isSegment the value for bio_refseq.is_segment
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public void setIsSegment(Boolean isSegment) {
        this.isSegment = isSegment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq.meta
     *
     * @return the value of bio_refseq.meta
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public String getMeta() {
        return meta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq.meta
     *
     * @param meta the value for bio_refseq.meta
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    public void setMeta(String meta) {
        this.meta = meta;
    }
}