package com.xjtlu.bio.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BioRefseqMetaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public BioRefseqMetaExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRefseqIdIsNull() {
            addCriterion("refseq_id is null");
            return (Criteria) this;
        }

        public Criteria andRefseqIdIsNotNull() {
            addCriterion("refseq_id is not null");
            return (Criteria) this;
        }

        public Criteria andRefseqIdEqualTo(Long value) {
            addCriterion("refseq_id =", value, "refseqId");
            return (Criteria) this;
        }

        public Criteria andRefseqIdNotEqualTo(Long value) {
            addCriterion("refseq_id <>", value, "refseqId");
            return (Criteria) this;
        }

        public Criteria andRefseqIdGreaterThan(Long value) {
            addCriterion("refseq_id >", value, "refseqId");
            return (Criteria) this;
        }

        public Criteria andRefseqIdGreaterThanOrEqualTo(Long value) {
            addCriterion("refseq_id >=", value, "refseqId");
            return (Criteria) this;
        }

        public Criteria andRefseqIdLessThan(Long value) {
            addCriterion("refseq_id <", value, "refseqId");
            return (Criteria) this;
        }

        public Criteria andRefseqIdLessThanOrEqualTo(Long value) {
            addCriterion("refseq_id <=", value, "refseqId");
            return (Criteria) this;
        }

        public Criteria andRefseqIdIn(List<Long> values) {
            addCriterion("refseq_id in", values, "refseqId");
            return (Criteria) this;
        }

        public Criteria andRefseqIdNotIn(List<Long> values) {
            addCriterion("refseq_id not in", values, "refseqId");
            return (Criteria) this;
        }

        public Criteria andRefseqIdBetween(Long value1, Long value2) {
            addCriterion("refseq_id between", value1, value2, "refseqId");
            return (Criteria) this;
        }

        public Criteria andRefseqIdNotBetween(Long value1, Long value2) {
            addCriterion("refseq_id not between", value1, value2, "refseqId");
            return (Criteria) this;
        }

        public Criteria andAccessionIsNull() {
            addCriterion("accession is null");
            return (Criteria) this;
        }

        public Criteria andAccessionIsNotNull() {
            addCriterion("accession is not null");
            return (Criteria) this;
        }

        public Criteria andAccessionEqualTo(String value) {
            addCriterion("accession =", value, "accession");
            return (Criteria) this;
        }

        public Criteria andAccessionNotEqualTo(String value) {
            addCriterion("accession <>", value, "accession");
            return (Criteria) this;
        }

        public Criteria andAccessionGreaterThan(String value) {
            addCriterion("accession >", value, "accession");
            return (Criteria) this;
        }

        public Criteria andAccessionGreaterThanOrEqualTo(String value) {
            addCriterion("accession >=", value, "accession");
            return (Criteria) this;
        }

        public Criteria andAccessionLessThan(String value) {
            addCriterion("accession <", value, "accession");
            return (Criteria) this;
        }

        public Criteria andAccessionLessThanOrEqualTo(String value) {
            addCriterion("accession <=", value, "accession");
            return (Criteria) this;
        }

        public Criteria andAccessionLike(String value) {
            addCriterion("accession like", value, "accession");
            return (Criteria) this;
        }

        public Criteria andAccessionNotLike(String value) {
            addCriterion("accession not like", value, "accession");
            return (Criteria) this;
        }

        public Criteria andAccessionIn(List<String> values) {
            addCriterion("accession in", values, "accession");
            return (Criteria) this;
        }

        public Criteria andAccessionNotIn(List<String> values) {
            addCriterion("accession not in", values, "accession");
            return (Criteria) this;
        }

        public Criteria andAccessionBetween(String value1, String value2) {
            addCriterion("accession between", value1, value2, "accession");
            return (Criteria) this;
        }

        public Criteria andAccessionNotBetween(String value1, String value2) {
            addCriterion("accession not between", value1, value2, "accession");
            return (Criteria) this;
        }

        public Criteria andSourceDbIsNull() {
            addCriterion("source_db is null");
            return (Criteria) this;
        }

        public Criteria andSourceDbIsNotNull() {
            addCriterion("source_db is not null");
            return (Criteria) this;
        }

        public Criteria andSourceDbEqualTo(String value) {
            addCriterion("source_db =", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbNotEqualTo(String value) {
            addCriterion("source_db <>", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbGreaterThan(String value) {
            addCriterion("source_db >", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbGreaterThanOrEqualTo(String value) {
            addCriterion("source_db >=", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbLessThan(String value) {
            addCriterion("source_db <", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbLessThanOrEqualTo(String value) {
            addCriterion("source_db <=", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbLike(String value) {
            addCriterion("source_db like", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbNotLike(String value) {
            addCriterion("source_db not like", value, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbIn(List<String> values) {
            addCriterion("source_db in", values, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbNotIn(List<String> values) {
            addCriterion("source_db not in", values, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbBetween(String value1, String value2) {
            addCriterion("source_db between", value1, value2, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andSourceDbNotBetween(String value1, String value2) {
            addCriterion("source_db not between", value1, value2, "sourceDb");
            return (Criteria) this;
        }

        public Criteria andTaxIdIsNull() {
            addCriterion("tax_id is null");
            return (Criteria) this;
        }

        public Criteria andTaxIdIsNotNull() {
            addCriterion("tax_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaxIdEqualTo(Integer value) {
            addCriterion("tax_id =", value, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdNotEqualTo(Integer value) {
            addCriterion("tax_id <>", value, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdGreaterThan(Integer value) {
            addCriterion("tax_id >", value, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tax_id >=", value, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdLessThan(Integer value) {
            addCriterion("tax_id <", value, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdLessThanOrEqualTo(Integer value) {
            addCriterion("tax_id <=", value, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdIn(List<Integer> values) {
            addCriterion("tax_id in", values, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdNotIn(List<Integer> values) {
            addCriterion("tax_id not in", values, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdBetween(Integer value1, Integer value2) {
            addCriterion("tax_id between", value1, value2, "taxId");
            return (Criteria) this;
        }

        public Criteria andTaxIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tax_id not between", value1, value2, "taxId");
            return (Criteria) this;
        }

        public Criteria andOrganismNameIsNull() {
            addCriterion("organism_name is null");
            return (Criteria) this;
        }

        public Criteria andOrganismNameIsNotNull() {
            addCriterion("organism_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrganismNameEqualTo(String value) {
            addCriterion("organism_name =", value, "organismName");
            return (Criteria) this;
        }

        public Criteria andOrganismNameNotEqualTo(String value) {
            addCriterion("organism_name <>", value, "organismName");
            return (Criteria) this;
        }

        public Criteria andOrganismNameGreaterThan(String value) {
            addCriterion("organism_name >", value, "organismName");
            return (Criteria) this;
        }

        public Criteria andOrganismNameGreaterThanOrEqualTo(String value) {
            addCriterion("organism_name >=", value, "organismName");
            return (Criteria) this;
        }

        public Criteria andOrganismNameLessThan(String value) {
            addCriterion("organism_name <", value, "organismName");
            return (Criteria) this;
        }

        public Criteria andOrganismNameLessThanOrEqualTo(String value) {
            addCriterion("organism_name <=", value, "organismName");
            return (Criteria) this;
        }

        public Criteria andOrganismNameLike(String value) {
            addCriterion("organism_name like", value, "organismName");
            return (Criteria) this;
        }

        public Criteria andOrganismNameNotLike(String value) {
            addCriterion("organism_name not like", value, "organismName");
            return (Criteria) this;
        }

        public Criteria andOrganismNameIn(List<String> values) {
            addCriterion("organism_name in", values, "organismName");
            return (Criteria) this;
        }

        public Criteria andOrganismNameNotIn(List<String> values) {
            addCriterion("organism_name not in", values, "organismName");
            return (Criteria) this;
        }

        public Criteria andOrganismNameBetween(String value1, String value2) {
            addCriterion("organism_name between", value1, value2, "organismName");
            return (Criteria) this;
        }

        public Criteria andOrganismNameNotBetween(String value1, String value2) {
            addCriterion("organism_name not between", value1, value2, "organismName");
            return (Criteria) this;
        }

        public Criteria andGenomeLengthIsNull() {
            addCriterion("genome_length is null");
            return (Criteria) this;
        }

        public Criteria andGenomeLengthIsNotNull() {
            addCriterion("genome_length is not null");
            return (Criteria) this;
        }

        public Criteria andGenomeLengthEqualTo(Integer value) {
            addCriterion("genome_length =", value, "genomeLength");
            return (Criteria) this;
        }

        public Criteria andGenomeLengthNotEqualTo(Integer value) {
            addCriterion("genome_length <>", value, "genomeLength");
            return (Criteria) this;
        }

        public Criteria andGenomeLengthGreaterThan(Integer value) {
            addCriterion("genome_length >", value, "genomeLength");
            return (Criteria) this;
        }

        public Criteria andGenomeLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("genome_length >=", value, "genomeLength");
            return (Criteria) this;
        }

        public Criteria andGenomeLengthLessThan(Integer value) {
            addCriterion("genome_length <", value, "genomeLength");
            return (Criteria) this;
        }

        public Criteria andGenomeLengthLessThanOrEqualTo(Integer value) {
            addCriterion("genome_length <=", value, "genomeLength");
            return (Criteria) this;
        }

        public Criteria andGenomeLengthIn(List<Integer> values) {
            addCriterion("genome_length in", values, "genomeLength");
            return (Criteria) this;
        }

        public Criteria andGenomeLengthNotIn(List<Integer> values) {
            addCriterion("genome_length not in", values, "genomeLength");
            return (Criteria) this;
        }

        public Criteria andGenomeLengthBetween(Integer value1, Integer value2) {
            addCriterion("genome_length between", value1, value2, "genomeLength");
            return (Criteria) this;
        }

        public Criteria andGenomeLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("genome_length not between", value1, value2, "genomeLength");
            return (Criteria) this;
        }

        public Criteria andCompletenessIsNull() {
            addCriterion("completeness is null");
            return (Criteria) this;
        }

        public Criteria andCompletenessIsNotNull() {
            addCriterion("completeness is not null");
            return (Criteria) this;
        }

        public Criteria andCompletenessEqualTo(String value) {
            addCriterion("completeness =", value, "completeness");
            return (Criteria) this;
        }

        public Criteria andCompletenessNotEqualTo(String value) {
            addCriterion("completeness <>", value, "completeness");
            return (Criteria) this;
        }

        public Criteria andCompletenessGreaterThan(String value) {
            addCriterion("completeness >", value, "completeness");
            return (Criteria) this;
        }

        public Criteria andCompletenessGreaterThanOrEqualTo(String value) {
            addCriterion("completeness >=", value, "completeness");
            return (Criteria) this;
        }

        public Criteria andCompletenessLessThan(String value) {
            addCriterion("completeness <", value, "completeness");
            return (Criteria) this;
        }

        public Criteria andCompletenessLessThanOrEqualTo(String value) {
            addCriterion("completeness <=", value, "completeness");
            return (Criteria) this;
        }

        public Criteria andCompletenessLike(String value) {
            addCriterion("completeness like", value, "completeness");
            return (Criteria) this;
        }

        public Criteria andCompletenessNotLike(String value) {
            addCriterion("completeness not like", value, "completeness");
            return (Criteria) this;
        }

        public Criteria andCompletenessIn(List<String> values) {
            addCriterion("completeness in", values, "completeness");
            return (Criteria) this;
        }

        public Criteria andCompletenessNotIn(List<String> values) {
            addCriterion("completeness not in", values, "completeness");
            return (Criteria) this;
        }

        public Criteria andCompletenessBetween(String value1, String value2) {
            addCriterion("completeness between", value1, value2, "completeness");
            return (Criteria) this;
        }

        public Criteria andCompletenessNotBetween(String value1, String value2) {
            addCriterion("completeness not between", value1, value2, "completeness");
            return (Criteria) this;
        }

        public Criteria andIsAnnotatedIsNull() {
            addCriterion("is_annotated is null");
            return (Criteria) this;
        }

        public Criteria andIsAnnotatedIsNotNull() {
            addCriterion("is_annotated is not null");
            return (Criteria) this;
        }

        public Criteria andIsAnnotatedEqualTo(Boolean value) {
            addCriterion("is_annotated =", value, "isAnnotated");
            return (Criteria) this;
        }

        public Criteria andIsAnnotatedNotEqualTo(Boolean value) {
            addCriterion("is_annotated <>", value, "isAnnotated");
            return (Criteria) this;
        }

        public Criteria andIsAnnotatedGreaterThan(Boolean value) {
            addCriterion("is_annotated >", value, "isAnnotated");
            return (Criteria) this;
        }

        public Criteria andIsAnnotatedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_annotated >=", value, "isAnnotated");
            return (Criteria) this;
        }

        public Criteria andIsAnnotatedLessThan(Boolean value) {
            addCriterion("is_annotated <", value, "isAnnotated");
            return (Criteria) this;
        }

        public Criteria andIsAnnotatedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_annotated <=", value, "isAnnotated");
            return (Criteria) this;
        }

        public Criteria andIsAnnotatedIn(List<Boolean> values) {
            addCriterion("is_annotated in", values, "isAnnotated");
            return (Criteria) this;
        }

        public Criteria andIsAnnotatedNotIn(List<Boolean> values) {
            addCriterion("is_annotated not in", values, "isAnnotated");
            return (Criteria) this;
        }

        public Criteria andIsAnnotatedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_annotated between", value1, value2, "isAnnotated");
            return (Criteria) this;
        }

        public Criteria andIsAnnotatedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_annotated not between", value1, value2, "isAnnotated");
            return (Criteria) this;
        }

        public Criteria andGeneCountIsNull() {
            addCriterion("gene_count is null");
            return (Criteria) this;
        }

        public Criteria andGeneCountIsNotNull() {
            addCriterion("gene_count is not null");
            return (Criteria) this;
        }

        public Criteria andGeneCountEqualTo(Integer value) {
            addCriterion("gene_count =", value, "geneCount");
            return (Criteria) this;
        }

        public Criteria andGeneCountNotEqualTo(Integer value) {
            addCriterion("gene_count <>", value, "geneCount");
            return (Criteria) this;
        }

        public Criteria andGeneCountGreaterThan(Integer value) {
            addCriterion("gene_count >", value, "geneCount");
            return (Criteria) this;
        }

        public Criteria andGeneCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("gene_count >=", value, "geneCount");
            return (Criteria) this;
        }

        public Criteria andGeneCountLessThan(Integer value) {
            addCriterion("gene_count <", value, "geneCount");
            return (Criteria) this;
        }

        public Criteria andGeneCountLessThanOrEqualTo(Integer value) {
            addCriterion("gene_count <=", value, "geneCount");
            return (Criteria) this;
        }

        public Criteria andGeneCountIn(List<Integer> values) {
            addCriterion("gene_count in", values, "geneCount");
            return (Criteria) this;
        }

        public Criteria andGeneCountNotIn(List<Integer> values) {
            addCriterion("gene_count not in", values, "geneCount");
            return (Criteria) this;
        }

        public Criteria andGeneCountBetween(Integer value1, Integer value2) {
            addCriterion("gene_count between", value1, value2, "geneCount");
            return (Criteria) this;
        }

        public Criteria andGeneCountNotBetween(Integer value1, Integer value2) {
            addCriterion("gene_count not between", value1, value2, "geneCount");
            return (Criteria) this;
        }

        public Criteria andProteinCountIsNull() {
            addCriterion("protein_count is null");
            return (Criteria) this;
        }

        public Criteria andProteinCountIsNotNull() {
            addCriterion("protein_count is not null");
            return (Criteria) this;
        }

        public Criteria andProteinCountEqualTo(Integer value) {
            addCriterion("protein_count =", value, "proteinCount");
            return (Criteria) this;
        }

        public Criteria andProteinCountNotEqualTo(Integer value) {
            addCriterion("protein_count <>", value, "proteinCount");
            return (Criteria) this;
        }

        public Criteria andProteinCountGreaterThan(Integer value) {
            addCriterion("protein_count >", value, "proteinCount");
            return (Criteria) this;
        }

        public Criteria andProteinCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("protein_count >=", value, "proteinCount");
            return (Criteria) this;
        }

        public Criteria andProteinCountLessThan(Integer value) {
            addCriterion("protein_count <", value, "proteinCount");
            return (Criteria) this;
        }

        public Criteria andProteinCountLessThanOrEqualTo(Integer value) {
            addCriterion("protein_count <=", value, "proteinCount");
            return (Criteria) this;
        }

        public Criteria andProteinCountIn(List<Integer> values) {
            addCriterion("protein_count in", values, "proteinCount");
            return (Criteria) this;
        }

        public Criteria andProteinCountNotIn(List<Integer> values) {
            addCriterion("protein_count not in", values, "proteinCount");
            return (Criteria) this;
        }

        public Criteria andProteinCountBetween(Integer value1, Integer value2) {
            addCriterion("protein_count between", value1, value2, "proteinCount");
            return (Criteria) this;
        }

        public Criteria andProteinCountNotBetween(Integer value1, Integer value2) {
            addCriterion("protein_count not between", value1, value2, "proteinCount");
            return (Criteria) this;
        }

        public Criteria andSegmentIsNull() {
            addCriterion("segment is null");
            return (Criteria) this;
        }

        public Criteria andSegmentIsNotNull() {
            addCriterion("segment is not null");
            return (Criteria) this;
        }

        public Criteria andSegmentEqualTo(String value) {
            addCriterion("segment =", value, "segment");
            return (Criteria) this;
        }

        public Criteria andSegmentNotEqualTo(String value) {
            addCriterion("segment <>", value, "segment");
            return (Criteria) this;
        }

        public Criteria andSegmentGreaterThan(String value) {
            addCriterion("segment >", value, "segment");
            return (Criteria) this;
        }

        public Criteria andSegmentGreaterThanOrEqualTo(String value) {
            addCriterion("segment >=", value, "segment");
            return (Criteria) this;
        }

        public Criteria andSegmentLessThan(String value) {
            addCriterion("segment <", value, "segment");
            return (Criteria) this;
        }

        public Criteria andSegmentLessThanOrEqualTo(String value) {
            addCriterion("segment <=", value, "segment");
            return (Criteria) this;
        }

        public Criteria andSegmentLike(String value) {
            addCriterion("segment like", value, "segment");
            return (Criteria) this;
        }

        public Criteria andSegmentNotLike(String value) {
            addCriterion("segment not like", value, "segment");
            return (Criteria) this;
        }

        public Criteria andSegmentIn(List<String> values) {
            addCriterion("segment in", values, "segment");
            return (Criteria) this;
        }

        public Criteria andSegmentNotIn(List<String> values) {
            addCriterion("segment not in", values, "segment");
            return (Criteria) this;
        }

        public Criteria andSegmentBetween(String value1, String value2) {
            addCriterion("segment between", value1, value2, "segment");
            return (Criteria) this;
        }

        public Criteria andSegmentNotBetween(String value1, String value2) {
            addCriterion("segment not between", value1, value2, "segment");
            return (Criteria) this;
        }

        public Criteria andBioprojectIsNull() {
            addCriterion("bioproject is null");
            return (Criteria) this;
        }

        public Criteria andBioprojectIsNotNull() {
            addCriterion("bioproject is not null");
            return (Criteria) this;
        }

        public Criteria andBioprojectEqualTo(String value) {
            addCriterion("bioproject =", value, "bioproject");
            return (Criteria) this;
        }

        public Criteria andBioprojectNotEqualTo(String value) {
            addCriterion("bioproject <>", value, "bioproject");
            return (Criteria) this;
        }

        public Criteria andBioprojectGreaterThan(String value) {
            addCriterion("bioproject >", value, "bioproject");
            return (Criteria) this;
        }

        public Criteria andBioprojectGreaterThanOrEqualTo(String value) {
            addCriterion("bioproject >=", value, "bioproject");
            return (Criteria) this;
        }

        public Criteria andBioprojectLessThan(String value) {
            addCriterion("bioproject <", value, "bioproject");
            return (Criteria) this;
        }

        public Criteria andBioprojectLessThanOrEqualTo(String value) {
            addCriterion("bioproject <=", value, "bioproject");
            return (Criteria) this;
        }

        public Criteria andBioprojectLike(String value) {
            addCriterion("bioproject like", value, "bioproject");
            return (Criteria) this;
        }

        public Criteria andBioprojectNotLike(String value) {
            addCriterion("bioproject not like", value, "bioproject");
            return (Criteria) this;
        }

        public Criteria andBioprojectIn(List<String> values) {
            addCriterion("bioproject in", values, "bioproject");
            return (Criteria) this;
        }

        public Criteria andBioprojectNotIn(List<String> values) {
            addCriterion("bioproject not in", values, "bioproject");
            return (Criteria) this;
        }

        public Criteria andBioprojectBetween(String value1, String value2) {
            addCriterion("bioproject between", value1, value2, "bioproject");
            return (Criteria) this;
        }

        public Criteria andBioprojectNotBetween(String value1, String value2) {
            addCriterion("bioproject not between", value1, value2, "bioproject");
            return (Criteria) this;
        }

        public Criteria andReleaseDateIsNull() {
            addCriterion("release_date is null");
            return (Criteria) this;
        }

        public Criteria andReleaseDateIsNotNull() {
            addCriterion("release_date is not null");
            return (Criteria) this;
        }

        public Criteria andReleaseDateEqualTo(Date value) {
            addCriterion("release_date =", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateNotEqualTo(Date value) {
            addCriterion("release_date <>", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateGreaterThan(Date value) {
            addCriterion("release_date >", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateGreaterThanOrEqualTo(Date value) {
            addCriterion("release_date >=", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateLessThan(Date value) {
            addCriterion("release_date <", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateLessThanOrEqualTo(Date value) {
            addCriterion("release_date <=", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateIn(List<Date> values) {
            addCriterion("release_date in", values, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateNotIn(List<Date> values) {
            addCriterion("release_date not in", values, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateBetween(Date value1, Date value2) {
            addCriterion("release_date between", value1, value2, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateNotBetween(Date value1, Date value2) {
            addCriterion("release_date not between", value1, value2, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andOrgTypeIsNull() {
            addCriterion("org_type is null");
            return (Criteria) this;
        }

        public Criteria andOrgTypeIsNotNull() {
            addCriterion("org_type is not null");
            return (Criteria) this;
        }

        public Criteria andOrgTypeEqualTo(Integer value) {
            addCriterion("org_type =", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeNotEqualTo(Integer value) {
            addCriterion("org_type <>", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeGreaterThan(Integer value) {
            addCriterion("org_type >", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("org_type >=", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeLessThan(Integer value) {
            addCriterion("org_type <", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeLessThanOrEqualTo(Integer value) {
            addCriterion("org_type <=", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeIn(List<Integer> values) {
            addCriterion("org_type in", values, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeNotIn(List<Integer> values) {
            addCriterion("org_type not in", values, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeBetween(Integer value1, Integer value2) {
            addCriterion("org_type between", value1, value2, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("org_type not between", value1, value2, "orgType");
            return (Criteria) this;
        }

        public Criteria andPathIsNull() {
            addCriterion("path is null");
            return (Criteria) this;
        }

        public Criteria andPathIsNotNull() {
            addCriterion("path is not null");
            return (Criteria) this;
        }

        public Criteria andPathEqualTo(String value) {
            addCriterion("path =", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotEqualTo(String value) {
            addCriterion("path <>", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathGreaterThan(String value) {
            addCriterion("path >", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathGreaterThanOrEqualTo(String value) {
            addCriterion("path >=", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLessThan(String value) {
            addCriterion("path <", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLessThanOrEqualTo(String value) {
            addCriterion("path <=", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLike(String value) {
            addCriterion("path like", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotLike(String value) {
            addCriterion("path not like", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathIn(List<String> values) {
            addCriterion("path in", values, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotIn(List<String> values) {
            addCriterion("path not in", values, "path");
            return (Criteria) this;
        }

        public Criteria andPathBetween(String value1, String value2) {
            addCriterion("path between", value1, value2, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotBetween(String value1, String value2) {
            addCriterion("path not between", value1, value2, "path");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated do_not_delete_during_merge Sat Nov 29 03:00:27 GMT 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}