package com.xjtlu.bio.entity;

import java.util.Date;

public class BioRefseqMeta {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.refseq_id
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private Long refseqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.accession
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private String accession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.source_db
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private String sourceDb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.tax_id
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private Integer taxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.organism_name
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private String organismName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.genome_length
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private Integer genomeLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.completeness
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private String completeness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.is_annotated
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private Boolean isAnnotated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.gene_count
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private Integer geneCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.protein_count
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private Integer proteinCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.segment
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private String segment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.bioproject
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private String bioproject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.release_date
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private Date releaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.update_date
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.org_type
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private Integer orgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.path
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_refseq_meta.raw_metadata
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    private String rawMetadata;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.refseq_id
     *
     * @return the value of bio_refseq_meta.refseq_id
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public Long getRefseqId() {
        return refseqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.refseq_id
     *
     * @param refseqId the value for bio_refseq_meta.refseq_id
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setRefseqId(Long refseqId) {
        this.refseqId = refseqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.accession
     *
     * @return the value of bio_refseq_meta.accession
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public String getAccession() {
        return accession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.accession
     *
     * @param accession the value for bio_refseq_meta.accession
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setAccession(String accession) {
        this.accession = accession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.source_db
     *
     * @return the value of bio_refseq_meta.source_db
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public String getSourceDb() {
        return sourceDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.source_db
     *
     * @param sourceDb the value for bio_refseq_meta.source_db
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setSourceDb(String sourceDb) {
        this.sourceDb = sourceDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.tax_id
     *
     * @return the value of bio_refseq_meta.tax_id
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public Integer getTaxId() {
        return taxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.tax_id
     *
     * @param taxId the value for bio_refseq_meta.tax_id
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setTaxId(Integer taxId) {
        this.taxId = taxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.organism_name
     *
     * @return the value of bio_refseq_meta.organism_name
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public String getOrganismName() {
        return organismName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.organism_name
     *
     * @param organismName the value for bio_refseq_meta.organism_name
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setOrganismName(String organismName) {
        this.organismName = organismName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.genome_length
     *
     * @return the value of bio_refseq_meta.genome_length
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public Integer getGenomeLength() {
        return genomeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.genome_length
     *
     * @param genomeLength the value for bio_refseq_meta.genome_length
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setGenomeLength(Integer genomeLength) {
        this.genomeLength = genomeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.completeness
     *
     * @return the value of bio_refseq_meta.completeness
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public String getCompleteness() {
        return completeness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.completeness
     *
     * @param completeness the value for bio_refseq_meta.completeness
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setCompleteness(String completeness) {
        this.completeness = completeness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.is_annotated
     *
     * @return the value of bio_refseq_meta.is_annotated
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public Boolean getIsAnnotated() {
        return isAnnotated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.is_annotated
     *
     * @param isAnnotated the value for bio_refseq_meta.is_annotated
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setIsAnnotated(Boolean isAnnotated) {
        this.isAnnotated = isAnnotated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.gene_count
     *
     * @return the value of bio_refseq_meta.gene_count
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public Integer getGeneCount() {
        return geneCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.gene_count
     *
     * @param geneCount the value for bio_refseq_meta.gene_count
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setGeneCount(Integer geneCount) {
        this.geneCount = geneCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.protein_count
     *
     * @return the value of bio_refseq_meta.protein_count
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public Integer getProteinCount() {
        return proteinCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.protein_count
     *
     * @param proteinCount the value for bio_refseq_meta.protein_count
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setProteinCount(Integer proteinCount) {
        this.proteinCount = proteinCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.segment
     *
     * @return the value of bio_refseq_meta.segment
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public String getSegment() {
        return segment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.segment
     *
     * @param segment the value for bio_refseq_meta.segment
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setSegment(String segment) {
        this.segment = segment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.bioproject
     *
     * @return the value of bio_refseq_meta.bioproject
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public String getBioproject() {
        return bioproject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.bioproject
     *
     * @param bioproject the value for bio_refseq_meta.bioproject
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setBioproject(String bioproject) {
        this.bioproject = bioproject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.release_date
     *
     * @return the value of bio_refseq_meta.release_date
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.release_date
     *
     * @param releaseDate the value for bio_refseq_meta.release_date
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.update_date
     *
     * @return the value of bio_refseq_meta.update_date
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.update_date
     *
     * @param updateDate the value for bio_refseq_meta.update_date
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.org_type
     *
     * @return the value of bio_refseq_meta.org_type
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public Integer getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.org_type
     *
     * @param orgType the value for bio_refseq_meta.org_type
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setOrgType(Integer orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.path
     *
     * @return the value of bio_refseq_meta.path
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.path
     *
     * @param path the value for bio_refseq_meta.path
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_refseq_meta.raw_metadata
     *
     * @return the value of bio_refseq_meta.raw_metadata
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public String getRawMetadata() {
        return rawMetadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_refseq_meta.raw_metadata
     *
     * @param rawMetadata the value for bio_refseq_meta.raw_metadata
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    public void setRawMetadata(String rawMetadata) {
        this.rawMetadata = rawMetadata;
    }
}