package com.xjtlu.bio.entity;

public class BioSample {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_sample.sid
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_sample.sample_name
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    private String sampleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_sample.is_pair
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    private Boolean isPair;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_sample.read1_url
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    private String read1Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_sample.read2_url
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    private String read2Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_sample.project_id
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_sample.created_by
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_sample.sample_type
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    private Integer sampleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_sample.pipeline_id
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    private Integer pipelineId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_sample.sid
     *
     * @return the value of bio_sample.sid
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_sample.sid
     *
     * @param sid the value for bio_sample.sid
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_sample.sample_name
     *
     * @return the value of bio_sample.sample_name
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public String getSampleName() {
        return sampleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_sample.sample_name
     *
     * @param sampleName the value for bio_sample.sample_name
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public void setSampleName(String sampleName) {
        this.sampleName = sampleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_sample.is_pair
     *
     * @return the value of bio_sample.is_pair
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public Boolean getIsPair() {
        return isPair;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_sample.is_pair
     *
     * @param isPair the value for bio_sample.is_pair
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public void setIsPair(Boolean isPair) {
        this.isPair = isPair;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_sample.read1_url
     *
     * @return the value of bio_sample.read1_url
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public String getRead1Url() {
        return read1Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_sample.read1_url
     *
     * @param read1Url the value for bio_sample.read1_url
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public void setRead1Url(String read1Url) {
        this.read1Url = read1Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_sample.read2_url
     *
     * @return the value of bio_sample.read2_url
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public String getRead2Url() {
        return read2Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_sample.read2_url
     *
     * @param read2Url the value for bio_sample.read2_url
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public void setRead2Url(String read2Url) {
        this.read2Url = read2Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_sample.project_id
     *
     * @return the value of bio_sample.project_id
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_sample.project_id
     *
     * @param projectId the value for bio_sample.project_id
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_sample.created_by
     *
     * @return the value of bio_sample.created_by
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_sample.created_by
     *
     * @param createdBy the value for bio_sample.created_by
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_sample.sample_type
     *
     * @return the value of bio_sample.sample_type
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public Integer getSampleType() {
        return sampleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_sample.sample_type
     *
     * @param sampleType the value for bio_sample.sample_type
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public void setSampleType(Integer sampleType) {
        this.sampleType = sampleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_sample.pipeline_id
     *
     * @return the value of bio_sample.pipeline_id
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public Integer getPipelineId() {
        return pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_sample.pipeline_id
     *
     * @param pipelineId the value for bio_sample.pipeline_id
     *
     * @mbg.generated Mon Oct 27 20:17:16 GMT 2025
     */
    public void setPipelineId(Integer pipelineId) {
        this.pipelineId = pipelineId;
    }
}