package com.xjtlu.bio.entity;

import java.util.ArrayList;
import java.util.List;

public class BioSampleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    public BioSampleExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSidIsNull() {
            addCriterion("sid is null");
            return (Criteria) this;
        }

        public Criteria andSidIsNotNull() {
            addCriterion("sid is not null");
            return (Criteria) this;
        }

        public Criteria andSidEqualTo(Long value) {
            addCriterion("sid =", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotEqualTo(Long value) {
            addCriterion("sid <>", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThan(Long value) {
            addCriterion("sid >", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThanOrEqualTo(Long value) {
            addCriterion("sid >=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThan(Long value) {
            addCriterion("sid <", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThanOrEqualTo(Long value) {
            addCriterion("sid <=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidIn(List<Long> values) {
            addCriterion("sid in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotIn(List<Long> values) {
            addCriterion("sid not in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidBetween(Long value1, Long value2) {
            addCriterion("sid between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotBetween(Long value1, Long value2) {
            addCriterion("sid not between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSampleNameIsNull() {
            addCriterion("sample_name is null");
            return (Criteria) this;
        }

        public Criteria andSampleNameIsNotNull() {
            addCriterion("sample_name is not null");
            return (Criteria) this;
        }

        public Criteria andSampleNameEqualTo(String value) {
            addCriterion("sample_name =", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameNotEqualTo(String value) {
            addCriterion("sample_name <>", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameGreaterThan(String value) {
            addCriterion("sample_name >", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameGreaterThanOrEqualTo(String value) {
            addCriterion("sample_name >=", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameLessThan(String value) {
            addCriterion("sample_name <", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameLessThanOrEqualTo(String value) {
            addCriterion("sample_name <=", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameLike(String value) {
            addCriterion("sample_name like", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameNotLike(String value) {
            addCriterion("sample_name not like", value, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameIn(List<String> values) {
            addCriterion("sample_name in", values, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameNotIn(List<String> values) {
            addCriterion("sample_name not in", values, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameBetween(String value1, String value2) {
            addCriterion("sample_name between", value1, value2, "sampleName");
            return (Criteria) this;
        }

        public Criteria andSampleNameNotBetween(String value1, String value2) {
            addCriterion("sample_name not between", value1, value2, "sampleName");
            return (Criteria) this;
        }

        public Criteria andIsPairIsNull() {
            addCriterion("is_pair is null");
            return (Criteria) this;
        }

        public Criteria andIsPairIsNotNull() {
            addCriterion("is_pair is not null");
            return (Criteria) this;
        }

        public Criteria andIsPairEqualTo(Boolean value) {
            addCriterion("is_pair =", value, "isPair");
            return (Criteria) this;
        }

        public Criteria andIsPairNotEqualTo(Boolean value) {
            addCriterion("is_pair <>", value, "isPair");
            return (Criteria) this;
        }

        public Criteria andIsPairGreaterThan(Boolean value) {
            addCriterion("is_pair >", value, "isPair");
            return (Criteria) this;
        }

        public Criteria andIsPairGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_pair >=", value, "isPair");
            return (Criteria) this;
        }

        public Criteria andIsPairLessThan(Boolean value) {
            addCriterion("is_pair <", value, "isPair");
            return (Criteria) this;
        }

        public Criteria andIsPairLessThanOrEqualTo(Boolean value) {
            addCriterion("is_pair <=", value, "isPair");
            return (Criteria) this;
        }

        public Criteria andIsPairIn(List<Boolean> values) {
            addCriterion("is_pair in", values, "isPair");
            return (Criteria) this;
        }

        public Criteria andIsPairNotIn(List<Boolean> values) {
            addCriterion("is_pair not in", values, "isPair");
            return (Criteria) this;
        }

        public Criteria andIsPairBetween(Boolean value1, Boolean value2) {
            addCriterion("is_pair between", value1, value2, "isPair");
            return (Criteria) this;
        }

        public Criteria andIsPairNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_pair not between", value1, value2, "isPair");
            return (Criteria) this;
        }

        public Criteria andRead1UrlIsNull() {
            addCriterion("read1_url is null");
            return (Criteria) this;
        }

        public Criteria andRead1UrlIsNotNull() {
            addCriterion("read1_url is not null");
            return (Criteria) this;
        }

        public Criteria andRead1UrlEqualTo(String value) {
            addCriterion("read1_url =", value, "read1Url");
            return (Criteria) this;
        }

        public Criteria andRead1UrlNotEqualTo(String value) {
            addCriterion("read1_url <>", value, "read1Url");
            return (Criteria) this;
        }

        public Criteria andRead1UrlGreaterThan(String value) {
            addCriterion("read1_url >", value, "read1Url");
            return (Criteria) this;
        }

        public Criteria andRead1UrlGreaterThanOrEqualTo(String value) {
            addCriterion("read1_url >=", value, "read1Url");
            return (Criteria) this;
        }

        public Criteria andRead1UrlLessThan(String value) {
            addCriterion("read1_url <", value, "read1Url");
            return (Criteria) this;
        }

        public Criteria andRead1UrlLessThanOrEqualTo(String value) {
            addCriterion("read1_url <=", value, "read1Url");
            return (Criteria) this;
        }

        public Criteria andRead1UrlLike(String value) {
            addCriterion("read1_url like", value, "read1Url");
            return (Criteria) this;
        }

        public Criteria andRead1UrlNotLike(String value) {
            addCriterion("read1_url not like", value, "read1Url");
            return (Criteria) this;
        }

        public Criteria andRead1UrlIn(List<String> values) {
            addCriterion("read1_url in", values, "read1Url");
            return (Criteria) this;
        }

        public Criteria andRead1UrlNotIn(List<String> values) {
            addCriterion("read1_url not in", values, "read1Url");
            return (Criteria) this;
        }

        public Criteria andRead1UrlBetween(String value1, String value2) {
            addCriterion("read1_url between", value1, value2, "read1Url");
            return (Criteria) this;
        }

        public Criteria andRead1UrlNotBetween(String value1, String value2) {
            addCriterion("read1_url not between", value1, value2, "read1Url");
            return (Criteria) this;
        }

        public Criteria andRead2UrlIsNull() {
            addCriterion("read2_url is null");
            return (Criteria) this;
        }

        public Criteria andRead2UrlIsNotNull() {
            addCriterion("read2_url is not null");
            return (Criteria) this;
        }

        public Criteria andRead2UrlEqualTo(String value) {
            addCriterion("read2_url =", value, "read2Url");
            return (Criteria) this;
        }

        public Criteria andRead2UrlNotEqualTo(String value) {
            addCriterion("read2_url <>", value, "read2Url");
            return (Criteria) this;
        }

        public Criteria andRead2UrlGreaterThan(String value) {
            addCriterion("read2_url >", value, "read2Url");
            return (Criteria) this;
        }

        public Criteria andRead2UrlGreaterThanOrEqualTo(String value) {
            addCriterion("read2_url >=", value, "read2Url");
            return (Criteria) this;
        }

        public Criteria andRead2UrlLessThan(String value) {
            addCriterion("read2_url <", value, "read2Url");
            return (Criteria) this;
        }

        public Criteria andRead2UrlLessThanOrEqualTo(String value) {
            addCriterion("read2_url <=", value, "read2Url");
            return (Criteria) this;
        }

        public Criteria andRead2UrlLike(String value) {
            addCriterion("read2_url like", value, "read2Url");
            return (Criteria) this;
        }

        public Criteria andRead2UrlNotLike(String value) {
            addCriterion("read2_url not like", value, "read2Url");
            return (Criteria) this;
        }

        public Criteria andRead2UrlIn(List<String> values) {
            addCriterion("read2_url in", values, "read2Url");
            return (Criteria) this;
        }

        public Criteria andRead2UrlNotIn(List<String> values) {
            addCriterion("read2_url not in", values, "read2Url");
            return (Criteria) this;
        }

        public Criteria andRead2UrlBetween(String value1, String value2) {
            addCriterion("read2_url between", value1, value2, "read2Url");
            return (Criteria) this;
        }

        public Criteria andRead2UrlNotBetween(String value1, String value2) {
            addCriterion("read2_url not between", value1, value2, "read2Url");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(Integer value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(Integer value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(Integer value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(Integer value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(Integer value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(Integer value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<Integer> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<Integer> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(Integer value1, Integer value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(Integer value1, Integer value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andSampleTypeIsNull() {
            addCriterion("sample_type is null");
            return (Criteria) this;
        }

        public Criteria andSampleTypeIsNotNull() {
            addCriterion("sample_type is not null");
            return (Criteria) this;
        }

        public Criteria andSampleTypeEqualTo(Integer value) {
            addCriterion("sample_type =", value, "sampleType");
            return (Criteria) this;
        }

        public Criteria andSampleTypeNotEqualTo(Integer value) {
            addCriterion("sample_type <>", value, "sampleType");
            return (Criteria) this;
        }

        public Criteria andSampleTypeGreaterThan(Integer value) {
            addCriterion("sample_type >", value, "sampleType");
            return (Criteria) this;
        }

        public Criteria andSampleTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("sample_type >=", value, "sampleType");
            return (Criteria) this;
        }

        public Criteria andSampleTypeLessThan(Integer value) {
            addCriterion("sample_type <", value, "sampleType");
            return (Criteria) this;
        }

        public Criteria andSampleTypeLessThanOrEqualTo(Integer value) {
            addCriterion("sample_type <=", value, "sampleType");
            return (Criteria) this;
        }

        public Criteria andSampleTypeIn(List<Integer> values) {
            addCriterion("sample_type in", values, "sampleType");
            return (Criteria) this;
        }

        public Criteria andSampleTypeNotIn(List<Integer> values) {
            addCriterion("sample_type not in", values, "sampleType");
            return (Criteria) this;
        }

        public Criteria andSampleTypeBetween(Integer value1, Integer value2) {
            addCriterion("sample_type between", value1, value2, "sampleType");
            return (Criteria) this;
        }

        public Criteria andSampleTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("sample_type not between", value1, value2, "sampleType");
            return (Criteria) this;
        }

        public Criteria andPipelineIdIsNull() {
            addCriterion("pipeline_id is null");
            return (Criteria) this;
        }

        public Criteria andPipelineIdIsNotNull() {
            addCriterion("pipeline_id is not null");
            return (Criteria) this;
        }

        public Criteria andPipelineIdEqualTo(Integer value) {
            addCriterion("pipeline_id =", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdNotEqualTo(Integer value) {
            addCriterion("pipeline_id <>", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdGreaterThan(Integer value) {
            addCriterion("pipeline_id >", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pipeline_id >=", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdLessThan(Integer value) {
            addCriterion("pipeline_id <", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdLessThanOrEqualTo(Integer value) {
            addCriterion("pipeline_id <=", value, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdIn(List<Integer> values) {
            addCriterion("pipeline_id in", values, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdNotIn(List<Integer> values) {
            addCriterion("pipeline_id not in", values, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdBetween(Integer value1, Integer value2) {
            addCriterion("pipeline_id between", value1, value2, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andPipelineIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pipeline_id not between", value1, value2, "pipelineId");
            return (Criteria) this;
        }

        public Criteria andColumnNameIsNull() {
            addCriterion("column_name is null");
            return (Criteria) this;
        }

        public Criteria andColumnNameIsNotNull() {
            addCriterion("column_name is not null");
            return (Criteria) this;
        }

        public Criteria andColumnNameEqualTo(Integer value) {
            addCriterion("column_name =", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotEqualTo(Integer value) {
            addCriterion("column_name <>", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameGreaterThan(Integer value) {
            addCriterion("column_name >", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameGreaterThanOrEqualTo(Integer value) {
            addCriterion("column_name >=", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameLessThan(Integer value) {
            addCriterion("column_name <", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameLessThanOrEqualTo(Integer value) {
            addCriterion("column_name <=", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameIn(List<Integer> values) {
            addCriterion("column_name in", values, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotIn(List<Integer> values) {
            addCriterion("column_name not in", values, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameBetween(Integer value1, Integer value2) {
            addCriterion("column_name between", value1, value2, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotBetween(Integer value1, Integer value2) {
            addCriterion("column_name not between", value1, value2, "columnName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bio_sample
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 31 03:51:39 GMT 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bio_sample
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}