package com.xjtlu.bio.entity;

public class BioTaxHost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_tax_host.tax_host_id
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    private Integer taxHostId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_tax_host.tax_id
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    private Integer taxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_tax_host.host_name
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    private String hostName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_tax_host.tax_host_id
     *
     * @return the value of bio_tax_host.tax_host_id
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    public Integer getTaxHostId() {
        return taxHostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_tax_host.tax_host_id
     *
     * @param taxHostId the value for bio_tax_host.tax_host_id
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    public void setTaxHostId(Integer taxHostId) {
        this.taxHostId = taxHostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_tax_host.tax_id
     *
     * @return the value of bio_tax_host.tax_id
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    public Integer getTaxId() {
        return taxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_tax_host.tax_id
     *
     * @param taxId the value for bio_tax_host.tax_id
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    public void setTaxId(Integer taxId) {
        this.taxId = taxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_tax_host.host_name
     *
     * @return the value of bio_tax_host.host_name
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_tax_host.host_name
     *
     * @param hostName the value for bio_tax_host.host_name
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    public void setHostName(String hostName) {
        this.hostName = hostName;
    }
}