package com.xjtlu.bio.entity;

public class BioUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_user.uid
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_user.name
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_user.password
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bio_user.role_id
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_user.uid
     *
     * @return the value of bio_user.uid
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_user.uid
     *
     * @param uid the value for bio_user.uid
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_user.name
     *
     * @return the value of bio_user.name
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_user.name
     *
     * @param name the value for bio_user.name
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_user.password
     *
     * @return the value of bio_user.password
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_user.password
     *
     * @param password the value for bio_user.password
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bio_user.role_id
     *
     * @return the value of bio_user.role_id
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bio_user.role_id
     *
     * @param roleId the value for bio_user.role_id
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}