package com.xjtlu.bio.mapper;

import com.xjtlu.bio.entity.BioAnalysisPipeline;
import com.xjtlu.bio.entity.BioAnalysisPipelineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BioAnalysisPipelineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sat Mar 28 15:51:48 EDT 2026
     */
    long countByExample(BioAnalysisPipelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sat Mar 28 15:51:48 EDT 2026
     */
    int deleteByExample(BioAnalysisPipelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sat Mar 28 15:51:48 EDT 2026
     */
    int deleteByPrimaryKey(Long pipelineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sat Mar 28 15:51:48 EDT 2026
     */
    int insert(BioAnalysisPipeline row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sat Mar 28 15:51:48 EDT 2026
     */
    int insertSelective(BioAnalysisPipeline row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sat Mar 28 15:51:48 EDT 2026
     */
    List<BioAnalysisPipeline> selectByExampleWithBLOBs(BioAnalysisPipelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sat Mar 28 15:51:48 EDT 2026
     */
    List<BioAnalysisPipeline> selectByExample(BioAnalysisPipelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sat Mar 28 15:51:48 EDT 2026
     */
    BioAnalysisPipeline selectByPrimaryKey(Long pipelineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sat Mar 28 15:51:48 EDT 2026
     */
    int updateByExampleSelective(@Param("row") BioAnalysisPipeline row, @Param("example") BioAnalysisPipelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sat Mar 28 15:51:48 EDT 2026
     */
    int updateByExampleWithBLOBs(@Param("row") BioAnalysisPipeline row, @Param("example") BioAnalysisPipelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sat Mar 28 15:51:48 EDT 2026
     */
    int updateByExample(@Param("row") BioAnalysisPipeline row, @Param("example") BioAnalysisPipelineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sat Mar 28 15:51:48 EDT 2026
     */
    int updateByPrimaryKeySelective(BioAnalysisPipeline row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sat Mar 28 15:51:48 EDT 2026
     */
    int updateByPrimaryKeyWithBLOBs(BioAnalysisPipeline row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_analysis_pipeline
     *
     * @mbg.generated Sat Mar 28 15:51:48 EDT 2026
     */
    int updateByPrimaryKey(BioAnalysisPipeline row);
}