package com.xjtlu.bio.mapper;

import com.xjtlu.bio.entity.BioPipelineInputFile;
import com.xjtlu.bio.entity.BioPipelineInputFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BioPipelineInputFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_input_file
     *
     * @mbg.generated Tue Mar 31 14:16:00 EDT 2026
     */
    long countByExample(BioPipelineInputFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_input_file
     *
     * @mbg.generated Tue Mar 31 14:16:00 EDT 2026
     */
    int deleteByExample(BioPipelineInputFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_input_file
     *
     * @mbg.generated Tue Mar 31 14:16:00 EDT 2026
     */
    int deleteByPrimaryKey(Long inputFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_input_file
     *
     * @mbg.generated Tue Mar 31 14:16:00 EDT 2026
     */
    int insert(BioPipelineInputFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_input_file
     *
     * @mbg.generated Tue Mar 31 14:16:00 EDT 2026
     */
    int insertSelective(BioPipelineInputFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_input_file
     *
     * @mbg.generated Tue Mar 31 14:16:00 EDT 2026
     */
    List<BioPipelineInputFile> selectByExample(BioPipelineInputFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_input_file
     *
     * @mbg.generated Tue Mar 31 14:16:00 EDT 2026
     */
    BioPipelineInputFile selectByPrimaryKey(Long inputFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_input_file
     *
     * @mbg.generated Tue Mar 31 14:16:00 EDT 2026
     */
    int updateByExampleSelective(@Param("row") BioPipelineInputFile row, @Param("example") BioPipelineInputFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_input_file
     *
     * @mbg.generated Tue Mar 31 14:16:00 EDT 2026
     */
    int updateByExample(@Param("row") BioPipelineInputFile row, @Param("example") BioPipelineInputFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_input_file
     *
     * @mbg.generated Tue Mar 31 14:16:00 EDT 2026
     */
    int updateByPrimaryKeySelective(BioPipelineInputFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_input_file
     *
     * @mbg.generated Tue Mar 31 14:16:00 EDT 2026
     */
    int updateByPrimaryKey(BioPipelineInputFile row);
}