package com.xjtlu.bio.mapper;

import com.xjtlu.bio.entity.BioProject;
import com.xjtlu.bio.entity.BioProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BioProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    long countByExample(BioProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int deleteByExample(BioProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int insert(BioProject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int insertSelective(BioProject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    List<BioProject> selectByExample(BioProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    BioProject selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int updateByExampleSelective(@Param("row") BioProject row, @Param("example") BioProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int updateByExample(@Param("row") BioProject row, @Param("example") BioProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int updateByPrimaryKeySelective(BioProject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int updateByPrimaryKey(BioProject row);
}