package com.xjtlu.bio.mapper;

import com.xjtlu.bio.entity.BioProject;
import com.xjtlu.bio.entity.BioProjectExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface BioProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    long countByExample(BioProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    int deleteByExample(BioProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    int deleteByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    int insert(BioProject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    int insertSelective(BioProject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    List<BioProject> selectByExample(BioProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    BioProject selectByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    int updateByExampleSelective(@Param("row") BioProject row, @Param("example") BioProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    int updateByExample(@Param("row") BioProject row, @Param("example") BioProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    int updateByPrimaryKeySelective(BioProject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_project
     *
     * @mbg.generated Fri Oct 31 03:51:39 GMT 2025
     */
    int updateByPrimaryKey(BioProject row);
}