package com.xjtlu.bio.mapper;

import com.xjtlu.bio.entity.BioPipelineStage;
import com.xjtlu.bio.entity.BioPipelineStageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BioPipelineStageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    long countByExample(BioPipelineStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int deleteByExample(BioPipelineStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int deleteByPrimaryKey(Long stageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int insert(BioPipelineStage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int insertSelective(BioPipelineStage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    List<BioPipelineStage> selectByExampleWithBLOBs(BioPipelineStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    List<BioPipelineStage> selectByExample(BioPipelineStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    BioPipelineStage selectByPrimaryKey(Long stageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int updateByExampleSelective(@Param("row") BioPipelineStage row, @Param("example") BioPipelineStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") BioPipelineStage row, @Param("example") BioPipelineStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int updateByExample(@Param("row") BioPipelineStage row, @Param("example") BioPipelineStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int updateByPrimaryKeySelective(BioPipelineStage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int updateByPrimaryKeyWithBLOBs(BioPipelineStage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_pipeline_stage
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int updateByPrimaryKey(BioPipelineStage row);
}