package com.xjtlu.bio.mapper;

import com.xjtlu.bio.entity.BioRole;
import com.xjtlu.bio.entity.BioRoleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


@Mapper
public interface BioRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_role
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    long countByExample(BioRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_role
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    int deleteByExample(BioRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_role
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_role
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    int insert(BioRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_role
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    int insertSelective(BioRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_role
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    List<BioRole> selectByExample(BioRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_role
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    BioRole selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_role
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    int updateByExampleSelective(@Param("row") BioRole row, @Param("example") BioRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_role
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    int updateByExample(@Param("row") BioRole row, @Param("example") BioRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_role
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    int updateByPrimaryKeySelective(BioRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_role
     *
     * @mbg.generated Wed Oct 15 02:55:01 GMT 2025
     */
    int updateByPrimaryKey(BioRole row);
}