package com.xjtlu.bio.mapper;

import com.xjtlu.bio.entity.BioReferenceSequence;
import com.xjtlu.bio.entity.BioReferenceSequenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BioReferenceSequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_reference_sequence
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    long countByExample(BioReferenceSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_reference_sequence
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    int deleteByExample(BioReferenceSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_reference_sequence
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    int deleteByPrimaryKey(Long referenceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_reference_sequence
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    int insert(BioReferenceSequence row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_reference_sequence
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    int insertSelective(BioReferenceSequence row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_reference_sequence
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    List<BioReferenceSequence> selectByExampleWithBLOBs(BioReferenceSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_reference_sequence
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    List<BioReferenceSequence> selectByExample(BioReferenceSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_reference_sequence
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    BioReferenceSequence selectByPrimaryKey(Long referenceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_reference_sequence
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    int updateByExampleSelective(@Param("row") BioReferenceSequence row, @Param("example") BioReferenceSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_reference_sequence
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    int updateByExampleWithBLOBs(@Param("row") BioReferenceSequence row, @Param("example") BioReferenceSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_reference_sequence
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    int updateByExample(@Param("row") BioReferenceSequence row, @Param("example") BioReferenceSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_reference_sequence
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    int updateByPrimaryKeySelective(BioReferenceSequence row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_reference_sequence
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    int updateByPrimaryKeyWithBLOBs(BioReferenceSequence row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_reference_sequence
     *
     * @mbg.generated Mon Sep 07 21:42:34 CST 2026
     */
    int updateByPrimaryKey(BioReferenceSequence row);
}