package com.xjtlu.bio.mapper;

import com.xjtlu.bio.entity.BioRefseq;
import com.xjtlu.bio.entity.BioRefseqExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BioRefseqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    long countByExample(BioRefseqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    int deleteByExample(BioRefseqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    int deleteByPrimaryKey(Long refId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    int insert(BioRefseq row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    int insertSelective(BioRefseq row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    List<BioRefseq> selectByExampleWithBLOBs(BioRefseqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    List<BioRefseq> selectByExample(BioRefseqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    BioRefseq selectByPrimaryKey(Long refId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    int updateByExampleSelective(@Param("row") BioRefseq row, @Param("example") BioRefseqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    int updateByExampleWithBLOBs(@Param("row") BioRefseq row, @Param("example") BioRefseqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    int updateByExample(@Param("row") BioRefseq row, @Param("example") BioRefseqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    int updateByPrimaryKeySelective(BioRefseq row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    int updateByPrimaryKeyWithBLOBs(BioRefseq row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq
     *
     * @mbg.generated Tue Mar 17 16:17:39 EDT 2026
     */
    int updateByPrimaryKey(BioRefseq row);
}