package com.xjtlu.bio.mapper;

import com.xjtlu.bio.entity.BioRefseqMeta;
import com.xjtlu.bio.entity.BioRefseqMetaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BioRefseqMetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    long countByExample(BioRefseqMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    int deleteByExample(BioRefseqMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    int deleteByPrimaryKey(Long refseqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    int insert(BioRefseqMeta row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    int insertSelective(BioRefseqMeta row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    List<BioRefseqMeta> selectByExampleWithBLOBs(BioRefseqMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    List<BioRefseqMeta> selectByExample(BioRefseqMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    BioRefseqMeta selectByPrimaryKey(Long refseqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    int updateByExampleSelective(@Param("row") BioRefseqMeta row, @Param("example") BioRefseqMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") BioRefseqMeta row, @Param("example") BioRefseqMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    int updateByExample(@Param("row") BioRefseqMeta row, @Param("example") BioRefseqMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    int updateByPrimaryKeySelective(BioRefseqMeta row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    int updateByPrimaryKeyWithBLOBs(BioRefseqMeta row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_refseq_meta
     *
     * @mbg.generated Sat Nov 29 03:00:27 GMT 2025
     */
    int updateByPrimaryKey(BioRefseqMeta row);
}