package com.xjtlu.bio.mapper;

import com.xjtlu.bio.entity.BioSample;
import com.xjtlu.bio.entity.BioSampleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BioSampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    long countByExample(BioSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int deleteByExample(BioSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int deleteByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int insert(BioSample row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int insertSelective(BioSample row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    List<BioSample> selectByExample(BioSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    BioSample selectByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int updateByExampleSelective(@Param("row") BioSample row, @Param("example") BioSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int updateByExample(@Param("row") BioSample row, @Param("example") BioSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int updateByPrimaryKeySelective(BioSample row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_sample
     *
     * @mbg.generated Tue Nov 04 23:07:22 GMT 2025
     */
    int updateByPrimaryKey(BioSample row);
}