package com.xjtlu.bio.mapper;

import com.xjtlu.bio.entity.BioTaxHost;
import com.xjtlu.bio.entity.BioTaxHostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BioTaxHostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_tax_host
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    long countByExample(BioTaxHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_tax_host
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    int deleteByExample(BioTaxHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_tax_host
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    int deleteByPrimaryKey(Integer taxHostId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_tax_host
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    int insert(BioTaxHost row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_tax_host
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    int insertSelective(BioTaxHost row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_tax_host
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    List<BioTaxHost> selectByExample(BioTaxHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_tax_host
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    BioTaxHost selectByPrimaryKey(Integer taxHostId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_tax_host
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    int updateByExampleSelective(@Param("row") BioTaxHost row, @Param("example") BioTaxHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_tax_host
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    int updateByExample(@Param("row") BioTaxHost row, @Param("example") BioTaxHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_tax_host
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    int updateByPrimaryKeySelective(BioTaxHost row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_tax_host
     *
     * @mbg.generated Thu Mar 19 17:40:17 EDT 2026
     */
    int updateByPrimaryKey(BioTaxHost row);
}