package com.xjtlu.bio.mapper;

import com.xjtlu.bio.entity.BioUser;
import com.xjtlu.bio.entity.BioUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BioUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_user
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    long countByExample(BioUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_user
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int deleteByExample(BioUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_user
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_user
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int insert(BioUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_user
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int insertSelective(BioUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_user
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    List<BioUser> selectByExample(BioUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_user
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    BioUser selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_user
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int updateByExampleSelective(@Param("row") BioUser row, @Param("example") BioUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_user
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int updateByExample(@Param("row") BioUser row, @Param("example") BioUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_user
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int updateByPrimaryKeySelective(BioUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bio_user
     *
     * @mbg.generated Sat Oct 25 00:37:22 GMT 2025
     */
    int updateByPrimaryKey(BioUser row);
}